using System;using System.Linq;using System.Collections.Generic;using System.Reflection;using System.Text.Json;using Emberfall;using UnityEngine;
namespace Emberfall{
public enum HeroClass{Vanguard,Arcanist,Ranger,Summoner}public enum VisualSurface{Metal,Crystal}public enum SkillVisualRecipe{Neutral,Fire,Ice}
public struct CombatDamage{public float Amount;public static implicit operator CombatDamage(float v)=>new CombatDamage{Amount=v};}
public class EnemyController:MonoBehaviour{}public class SummonedCompanion:MonoBehaviour{public bool EmpoweredAttackActive;}public class ProjectileVolleyBudget<T>{}
public class CombatModel:MonoBehaviour{}
public static class ProjectileVisualBridge{public static int Binds;public static void Bind(Transform body,Transform root,CombatModel model,bool arrow,TrailRenderer trail){Binds++;}}
public static class CombatReviewEvents{public static bool Enabled=false;public static void Emit(string s,int id,object target=null,int skill=0,string detail=null){}}
public static class CombatReviewObjectId{public static int Get(object x)=>1;}
public class DestructibleProp{public static bool FindProjectileHit(PlayerController p,Vector3 a,Vector3 b,float r,out DestructibleProp prop,out float f){prop=null;f=0;return false;}public void Impact(PlayerController p,int id,CombatDamage d){}}
public static class ProceduralVisuals{
static Mesh From(VisualMeshData d,string name)=>new Mesh{name=name,vertices=d.Vertices,normals=d.Normals,uv=d.Uv,triangles=d.Triangles};
public static Mesh WeatheredRock=From(VisualMeshRecipes.Rock(),"WeatheredRock");
public static GameObject Create(string name,PrimitiveType type,Material m){var o=new GameObject(name);o.AddComponent<MeshFilter>().sharedMesh=From(VisualMeshRecipes.RoundBody(type==PrimitiveType.Capsule,16,12),type.ToString());o.AddComponent<MeshRenderer>().sharedMaterial=m;return o;}public static void ApplySurface(Material m,VisualSurface v){}
}}
class Program{
static int checks;static void Check(bool b,string msg){checks++;if(!b)throw new Exception(msg);}
static object Field(object x,string n)=>x.GetType().GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(x);
static void Reset(){foreach(var o in GameObject.All.ToArray())UnityEngine.Object.Destroy(o);GameObject.All.Clear();typeof(AuthoredProjectileMeshes).GetMethod("Reset",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,null);Resources.Bad=null;CombatSight.Wall=float.PositiveInfinity;}
static CombatProjectile Latest()=>GameObject.All.Last(o=>o.GetComponent<CombatProjectile>()!=null).GetComponent<CombatProjectile>();
static Mesh Mesh(CombatProjectile p)=>((Transform)Field(p,"visualBody")).gameObject.GetComponent<MeshFilter>().sharedMesh;
static string Snapshot(CombatProjectile p){var fields=p.GetType().GetFields(BindingFlags.Instance|BindingFlags.NonPublic).Where(f=>f.FieldType.IsPrimitive||f.FieldType==typeof(CombatDamage)||f.FieldType==typeof(Vector3)).OrderBy(f=>f.Name);return JsonSerializer.Serialize(fields.Select(f=>new {f.Name,value=JsonSerializer.Serialize(f.GetValue(p),new JsonSerializerOptions{IncludeFields=true,IgnoreReadOnlyProperties=true})}).ToArray())+JsonSerializer.Serialize(new[]{p.transform.position,p.transform.localScale,p.transform.rotation*Vector3.up},new JsonSerializerOptions{IncludeFields=true,IgnoreReadOnlyProperties=true});}
static List<object> samples=new List<object>();static void Sample(string name,Mesh m,Transform t){var c=t.gameObject.GetComponent<MeshRenderer>().sharedMaterial.color;samples.Add(new{name,color=new[]{c.r,c.g,c.b},vertices=m.vertices.Select(v=>t.TransformPoint(v)).Select(v=>new[]{v.x,v.y,v.z}).ToArray(),triangles=m.triangles});}
static void Main(string[]args){Resources.Root=args[0];
foreach(bool reduced in new[]{false,true})foreach(bool mobile in new[]{false,true})foreach(var hero in new[]{HeroClass.Arcanist,HeroClass.Ranger,HeroClass.Summoner})foreach(bool arrow in new[]{false,true})foreach(bool companion in new[]{false,true}){
 Reset();EffectPreferences.ReducedEffects=reduced;Application.isMobilePlatform=mobile;var h=new GameObject("hero").AddComponent<PlayerController>();h.HeroClass=hero;h.CombatEpoch=6;var g=new GameSession{Player=h,HasStarted=true};var c=companion?new GameObject().AddComponent<SummonedCompanion>():null;var target=new GameObject().AddComponent<EnemyController>();var volley=new ProjectileVolleyBudget<EnemyController>();
 CombatProjectile.Friendly(h,g,new Vector3(2,5,3),Vector3.forward,9,(arrow?new Color(.38f,.88f,.65f):new Color(.4f,.7f,1f)),true,arrow,false,1.5f,22,target,3,.7f,0,37,c,volley,target,.2f);var p=Latest();var mesh=Mesh(p);var key=arrow?"ArrowBody":companion||hero==HeroClass.Summoner?"ContractBolt":"CasterBolt";Check(mesh.name.EndsWith(key),"real resource identity");Check(mesh.triangles.Length/3<=128,"projectile triangle budget");Check(ReferenceEquals(Field(p,"volley"),volley)&&ReferenceEquals(Field(p,"homingTarget"),target),"target volley preserved");Check((float)Field(p,"speed")==22&&(float)Field(p,"radius")==.38f*1.5f&&(float)Field(p,"lifetime")==2.5f,"real friendly simulation fields");
 if(arrow)Check((p.transform.TransformPoint(Vector3.up)-p.transform.position).z>0,"authored tip+Y follows unchanged flight+Z");string before=Snapshot(p);AuthoredProjectileMeshes.Enabled=false;CombatProjectile.Friendly(h,g,new Vector3(2,5,3),Vector3.forward,9,new Color(0,1,1),true,arrow,false,1.5f,22,target,3,.7f,0,37,c,volley,target,.2f);Check(Snapshot(Latest())==before,"authored off simulation snapshot unchanged");AuthoredProjectileMeshes.Enabled=true;
 var body=(Transform)Field(p,"visualBody");var trail=body.gameObject.GetComponent<TrailRenderer>();Check(trail.time==(reduced?.08f:arrow?.18f:.16f)&&trail.startWidth==(arrow?.14f:.16f)&&p.gameObject.GetComponent<TrailRenderer>()==null,"sculpted child trail budget");
 if(!reduced&&!mobile&&hero==HeroClass.Arcanist&&!companion){((Material)Field(Latest(),"bodyMaterial")).color=((Material)Field(p,"bodyMaterial")).color;Sample(key+" authored",mesh,body);Sample(key+" old",Mesh(Latest()),(Transform)Field(Latest(),"visualBody"));}
 var material=(Material)Field(p,"bodyMaterial");UnityEngine.Object.Destroy(p.gameObject);Check(material.Destroyed&&!mesh.Destroyed,"projectile owns material not shared authored mesh");
 }
 Reset();var player=new GameObject().AddComponent<PlayerController>();player.HeroClass=HeroClass.Summoner;var game=new GameSession{Player=player,HasStarted=true};
 CombatProjectile.BasicShot(player,game,new Vector3(0,1.2f,0),new Vector3(0,1.5f,5),7,new Color(.83f,.63f,1f),false,null);var basic=Latest();Check(Mesh(basic).name.EndsWith("ContractBolt"),"basic explicit hero contract identity");Check((float)Field(basic,"launchHeight")==1.2f&&(float)Field(basic,"aimedDistance")==5,"basic height/aim retained");Sample("ContractBolt authored",Mesh(basic),(Transform)Field(basic,"visualBody"));Sample("ContractBolt old",ProceduralVisuals.Create("old",PrimitiveType.Sphere,new Material(new Shader())).GetComponent<MeshFilter>().sharedMesh,(Transform)Field(basic,"visualBody"));
 CombatProjectile.Hostile(game,Vector3.zero,Vector3.forward,8);var hostile=Latest();Check(Mesh(hostile).name.EndsWith("HostileBolt"),"hostile identity");Check((bool)Field(hostile,"hostile")&&(float)Field(hostile,"radius")==.32f,"hostile collision retained");var color=((Material)Field(hostile,"bodyMaterial")).color;Check(color.r==1&&color.g==.31f&&color.b==.48f,"hostile red retained");Sample("HostileBolt authored",Mesh(hostile),(Transform)Field(hostile,"visualBody"));Sample("HostileBolt old",ProceduralVisuals.Create("old",PrimitiveType.Sphere,new Material(new Shader())).GetComponent<MeshFilter>().sharedMesh,(Transform)Field(hostile,"visualBody"));
 foreach(string failure in new[]{"missing","malformed"})foreach(string key in new[]{"ArrowBody","CasterBolt","ContractBolt","HostileBolt","MeteorRock","TrapCore"}){Reset();player=new GameObject("fallback owner").AddComponent<PlayerController>();Resources.BadGroup="BlenderProjectiles";Resources.BadName=key;Resources.Bad=failure;Check(AuthoredProjectileMeshes.Load(key)==null,"bad individual fallback");Check(AuthoredProjectileMeshes.Load(key=="ContractBolt"?"CasterBolt":"ContractBolt")!=null,"bad resource independent");if(key=="MeteorRock"){var fallback=new GameObject().AddComponent<AreaCosmetics>();fallback.Setup(player,SkillVisualRecipe.Fire,-1,.7f,3,new Color(),true);Check(fallback.fallingOrb.GetComponent<MeshFilter>().sharedMesh==ProceduralVisuals.WeatheredRock,"meteor original mesh fallback");}if(key=="TrapCore")Check(AuthoredTrapVisual.Create(new GameObject().transform,new Color(),3)==null,"trap absent keeps old marker feedback");}
 Reset();player=new GameObject("area owner").AddComponent<PlayerController>();var rock=AuthoredProjectileMeshes.Load("MeteorRock");var old=ProceduralVisuals.WeatheredRock;Check(rock.triangles.Length<=old.triangles.Length,"meteor triangle reduction");for(int a=0;a<3;a++){Func<Vector3,float> axis=v=>a==0?v.x:a==1?v.y:v.z;Check(rock.vertices.Min(axis)>=old.vertices.Min(axis)-.0001f&&rock.vertices.Max(axis)<=old.vertices.Max(axis)+.0001f,"meteor old envelope");}
 var area=new GameObject("area").AddComponent<AreaCosmetics>();area.Setup(player,SkillVisualRecipe.Fire,-1,.7f,3,new Color(1,1,1),true);Check(area.fallingOrb.GetComponent<MeshFilter>().sharedMesh==rock,"actual meteor setup loads authored");Sample("MeteorRock authored",rock,area.fallingOrb.transform);Sample("MeteorRock old",old,area.fallingOrb.transform);Time.deltaTime=.1f;area.Advance(.35f);Check(Math.Abs(area.fallingOrb.transform.localPosition.y-6.875f)<.001f,"original quadratic descent");area.Advance(.7f);Check(area.fallingOrb==null,"exact original release retirement");
 player.HeroClass=HeroClass.Ranger;var trap=new GameObject("trap area").AddComponent<AreaCosmetics>();trap.Setup(player,SkillVisualRecipe.Neutral,1,.4f,3,new Color(.3f,1,.2f),false);Check(trap.trapCore!=null&&CombatVisualLease.Active==1,"actual trap first stage lease");var clip=trap.trapCore.GetComponent<MeshFilter>().sharedMesh;Check(clip.triangles.Length<=384,"trap clipped budget");Sample("TrapCore authored",clip,trap.trapCore.transform);trap.Advance(.39f);Check(trap.trapCore!=null,"trap preparation retained");trap.Advance(.4f);Check(trap.trapCore==null&&clip.Destroyed&&CombatVisualLease.Active==0,"trap contact cleanup owns clipped copy");
 var echo=new GameObject().AddComponent<AreaCosmetics>();echo.Setup(player,SkillVisualRecipe.Neutral,-1,.8f,3,new Color(),false);Check(echo.trapCore==null,"echo no fake trap identity");
 foreach(bool low in new[]{false,true})foreach(bool phone in new[]{false,true}){
 Reset();EffectPreferences.ReducedEffects=low;Application.isMobilePlatform=phone;int cap=low?12:phone?20:32;var parent=new GameObject("area gameplay");var first=AuthoredTrapVisual.Create(parent.transform,new Color(),3);var firstMesh=first.GetComponent<MeshFilter>().sharedMesh;for(int i=1;i<cap;i++)Check(AuthoredTrapVisual.Create(parent.transform,new Color(),3)!=null,"trap within existing tier cap");Check(AuthoredTrapVisual.Create(parent.transform,new Color(),3)==null&&CombatVisualLease.Active==cap,"trap denial keeps existing tier cap");var contact=new GameObject("actual contact");CombatVisualLease.Attach(contact,CombatVisualPriority.RealContact);Check(first.Destroyed&&firstMesh.Destroyed&&!parent.Destroyed,"real contact evicts visual child only");UnityEngine.Object.Destroy(parent);UnityEngine.Object.Destroy(contact);Check(CombatVisualLease.Active==0,"area retirement clears trap leases");
 }
 Reset();CombatSight.Wall=.22f;var coveredParent=new GameObject("cover");var covered=AuthoredTrapVisual.Create(coveredParent.transform,new Color(),3);if(covered!=null){foreach(var vertex in covered.GetComponent<MeshFilter>().sharedMesh.vertices)Check(vertex.x<=.2201f,"trap never crosses dynamic cover");}Check(AuthoredProjectileMeshes.Load("TrapCore")!=null,"cover clipping never destroys shared source");
 var shared=AuthoredProjectileMeshes.Load("TrapCore");Reset();Check(shared.Destroyed&&AuthoredProjectileMeshes.Load("TrapCore")!=shared,"subsystem reset releases and reloads");
 System.IO.File.WriteAllText(args[1],JsonSerializer.Serialize(samples));Console.WriteLine("PASS "+checks+" actual resource/factory identity, simulation snapshots, reduced/mobile trails, shared ownership, meteor/TRS and trap lifetime assertions. Managed Unity doubles, not engine validation.");}
}
