"""Actual class switch name normalization and per-class gem socket persistence."""
from pathlib import Path
import importlib.util,tempfile,subprocess,os,sys
root=Path(__file__).resolve().parents[1]
spec=importlib.util.spec_from_file_location('cv',root/'Tools/cloud-validation.py');cv=importlib.util.module_from_spec(spec);spec.loader.exec_module(cv)
program=r'''using System;using System.IO;using System.Linq;using UnityEngine;using Emberfall;
class Program {static int checks;static void Check(bool v,string reason){checks++;if(!v)throw new Exception(reason);}static string Json(object value)=>JsonUtility.ToJson(value,true);
static ProgressionService New(string root,HeroClass hero){var p=new ProgressionService(Path.Combine(root,Guid.NewGuid().ToString("N")));Check(p.CreateNewSlot(hero),"create");p.Profile.level=100;p.Save();return p;}
static void Switch(ProgressionService p,HeroClass target){var before=Json(p.Profile);var tx=p.PrepareClassSwitch(target,true);Check(tx!=null&&Json(p.Profile)==before,"prepare isolated");Check(p.CommitClassSwitch(tx,true),"durable switch");p.PublishClassSwitch(tx);Check(p.Profile.heroClass==target,"publish class");}
static void Main(string[] args){string root=args[0];Directory.CreateDirectory(root);
foreach(HeroClass from in Enum.GetValues(typeof(HeroClass)))foreach(HeroClass to in Enum.GetValues(typeof(HeroClass))){if(from==to)continue;var p=New(root,from);string id=p.Profile.weaponId;var item=p.Profile.inventory.Single(x=>x.id==id);int attack=item.attack,rank=item.upgradeLevel;string armor=p.Profile.inventory.Single(x=>x.slot==ItemSlot.Armor).name;
Switch(p,to);string name=to==HeroClass.Vanguard?"长剑":to==HeroClass.Arcanist?"法杖":to==HeroClass.Ranger?"长弓":"法器";item=p.Profile.inventory.Single(x=>x.id==id);Check(item.name=="初行"+name&&item.attack==attack&&item.upgradeLevel==rank,"12 directed name switches preserve stats rank identity");Check(p.Profile.inventory.Single(x=>x.slot==ItemSlot.Armor).name==armor,"armor name unchanged");Check(p.LoadSlot(p.CurrentSlotId)&&p.Profile.inventory.Single(x=>x.id==id).name=="初行"+name,"name persisted");Switch(p,from);}
        {
            var p=New(root,HeroClass.Vanguard);var weapon=p.Profile.inventory.Single(x=>x.slot==ItemSlot.Weapon);
            weapon.name="烬王长剑";weapon.locked=true;
            var pending=JsonUtility.FromJson<ItemData>(Json(weapon));pending.id="pending-name";pending.name="旅者长剑";p.Profile.pendingLoot.Add(pending);
            var recovery=JsonUtility.FromJson<ItemData>(Json(weapon));recovery.id="recovery-name";recovery.name="苍蓝长剑";p.Profile.recoveryLoot.Add(recovery);
            var dungeon=JsonUtility.FromJson<ItemData>(Json(weapon));dungeon.id="dungeon-name";dungeon.name="星辉长剑";p.Profile.dungeonLoot.Add(dungeon);
            foreach(var mechanic in new[]{EquipmentMechanic.ReturningBlade,EquipmentMechanic.WeaponPower,EquipmentMechanic.WeaponPrecision,EquipmentMechanic.WeaponRuin,EquipmentMechanic.CinderTrail})
                p.Profile.attachments.Add(new MechanicAttachment{id="gem-"+mechanic,mechanic=mechanic,rarity=Rarity.Epic,upgradeRank=3,ascensionRank=1,mounted=mechanic!=EquipmentMechanic.WeaponRuin&&mechanic!=EquipmentMechanic.CinderTrail});
            p.Save();
            Switch(p,HeroClass.Arcanist);
            Check(p.Profile.inventory.Single(x=>x.id==weapon.id).name=="烬王法杖"&&p.Profile.inventory.Concat(p.Profile.pendingLoot).Single(x=>x.id=="pending-name").name=="旅者法杖"&&p.Profile.inventory.Concat(p.Profile.recoveryLoot).Single(x=>x.id=="recovery-name").name=="苍蓝法杖"&&p.Profile.inventory.Concat(p.Profile.dungeonLoot).Single(x=>x.id=="dungeon-name").name=="星辉法杖","all item storage names follow class and preserve prefixes");
            Check(p.SetAttachmentMounted(EquipmentMechanic.WeaponPower,false,true)&&p.SetAttachmentMounted(EquipmentMechanic.CinderTrail,true,true)&&p.SetAttachmentMounted(EquipmentMechanic.WeaponRuin,true,true),"target mounts its own three weapon gems");
            Switch(p,HeroClass.Vanguard);
            Check(p.Attachment(EquipmentMechanic.ReturningBlade).mounted&&p.Attachment(EquipmentMechanic.WeaponPower).mounted&&p.Attachment(EquipmentMechanic.WeaponPrecision).mounted&&!p.Attachment(EquipmentMechanic.WeaponRuin).mounted,"source three weapon gems restored without losing one to slot cap");
            Check(p.Profile.attachments.Count==5&&p.Profile.attachments.All(x=>x.upgradeRank==3&&x.ascensionRank==1)&&p.Profile.inventory.Single(x=>x.id==weapon.id).locked,"gem identity ranks and gear lock preserved");
            var reload=new ProgressionService(p.SaveDirectory);Check(reload.LoadSlot(p.CurrentSlotId),"gem archive reload: "+reload.LastError);Switch(reload,HeroClass.Arcanist);
            Check(!reload.Attachment(EquipmentMechanic.WeaponPower).mounted&&reload.Attachment(EquipmentMechanic.WeaponPrecision).mounted&&reload.Attachment(EquipmentMechanic.WeaponRuin).mounted&&reload.Attachment(EquipmentMechanic.CinderTrail).mounted,"target weapon sockets restored after reload");
            Switch(reload,HeroClass.Vanguard);Check(reload.SellGem(EquipmentMechanic.WeaponRuin,true),"dormant class use does not block sale");Switch(reload,HeroClass.Arcanist);
            Check(reload.Attachment(EquipmentMechanic.WeaponRuin)==null,"sold gem is never resurrected by class archive");
        }
{var p=New(root,HeroClass.Vanguard);var tx=p.PrepareClassSwitch(HeroClass.Arcanist,true);string before=Json(p.Profile);Directory.CreateDirectory(p.SaveFilePath+".tmp");Check(!p.CommitClassSwitch(tx,true)&&Json(p.Profile)==before,"disk failure preserves names and sockets");Directory.Delete(p.SaveFilePath+".tmp");}
{var p=New(root,HeroClass.Vanguard);foreach(var mechanic in new[]{EquipmentMechanic.CinderTrail,EquipmentMechanic.WeaponPower,EquipmentMechanic.WeaponPrecision,EquipmentMechanic.WeaponRuin})p.Profile.attachments.Add(new MechanicAttachment{id="third-"+mechanic,mechanic=mechanic,rarity=Rarity.Epic,ascensionRank=1,mounted=true});p.Save();Switch(p,HeroClass.Arcanist);Check(p.Attachment(EquipmentMechanic.WeaponRuin).mounted&&p.Attachment(EquipmentMechanic.WeaponPower).mounted&&p.Attachment(EquipmentMechanic.WeaponPrecision).mounted&&!p.Attachment(EquipmentMechanic.CinderTrail).mounted,"first class visit preserves all three universal gems instead of losing third to dormant exclusive gem");Switch(p,HeroClass.Vanguard);Check(p.Attachment(EquipmentMechanic.WeaponRuin).mounted,"third gem retained returning class");p.Profile.classStates[(int)HeroClass.Arcanist].mountedGems=null;p.Attachment(EquipmentMechanic.CinderTrail).mounted=true;p.Save();Switch(p,HeroClass.Arcanist);Check(p.Attachment(EquipmentMechanic.WeaponRuin).mounted&&!p.Attachment(EquipmentMechanic.CinderTrail).mounted,"legacy class state without socket archive preserves third universal gem");}
{var p=New(root,HeroClass.Vanguard);var basis=p.GetStats();p.Profile.attachments.Add(new MechanicAttachment{id="ruin-mechanism",mechanic=EquipmentMechanic.WeaponRuin,rarity=Rarity.Epic,ascensionRank=1,mounted=true});p.Save();var a=p.GetStats();Check(Math.Abs(a.CritDamageBonus-basis.CritDamageBonus-BuildCatalog.GemAttributeValue(EquipmentMechanic.WeaponRuin,Rarity.Epic,0)-.15f)<.0001f&&a.GemHealthyDamage==basis.GemHealthyDamage&&a.GemLowHealthDamage==basis.GemLowHealthDamage,"ruin form A adds critical damage and no duplicated health mechanism");p.Attachment(EquipmentMechanic.WeaponRuin).variant=1;p.Save();var b=p.GetStats();Check(Math.Abs(b.CritDamageBonus-a.CritDamageBonus-.075f)<.0001f&&Math.Abs(b.CritChance-Math.Max(0,a.CritChance-.02f))<.0001f,"ruin form B trades two percent critical chance for stronger critical damage");Check(BuildCatalog.GemFormName(EquipmentMechanic.WeaponRuin,0)!=BuildCatalog.GemFormName(EquipmentMechanic.WeaponPrecision,0)&&BuildCatalog.GemFormDescription(EquipmentMechanic.WeaponRuin,1,1).Contains("暴击率 -2%"),"distinct mechanism and honest tradeoff text");}
Console.WriteLine("PASS "+checks+" class equipment name and gem socket assertions");}}
'''
with tempfile.TemporaryDirectory(prefix='class-equipment-') as tmp:
 p=Path(tmp);(p/'NuGet.Config').write_text('<configuration><packageSources><clear/></packageSources></configuration>')
 names=['SkillRuntime','GameTypes','ProgressionService','ProgressionService.Attachments','ProgressionService.AutomaticGrowth','ProgressionService.Trading','ProgressionService.Smith','CombatBalance','SkillDamageBudgets','HubTravelRules','MasteryCoreRuntime','TierRewardRules','TierRewardBand','ProgressionGoalState','ChapterProgression','ProgressionService.Chapter','ProgressionService.Reforge','ReforgeQuote','RoomTactics','CombatImpactBatch','SafeSaveFlow']
 sources=[root/('Assets/Scripts/Core/'+name+'.cs') for name in names]+[root/'Tests/ProgressionTests.cs']
 project=cv.write_project(p/'project',sources,program)
 subprocess.run([sys.argv[1] if len(sys.argv)>1 else '/Applications/Unity/Hub/Editor/6000.6.4f1/Unity.app/Contents/Resources/Scripting/DotNetSdk/dotnet','run','--project',str(project),'--',str(p/'saves')],check=True,env=dict(os.environ,DOTNET_CLI_HOME=str(p/'cli'),DOTNET_NOLOGO='1'))
