"""Real skill helper and Friendly factory. Unity allocation/rendering APIs doubled."""
from pathlib import Path
import sys,os,tempfile,subprocess
r=Path(__file__).resolve().parents[1];ns={'__file__':str(r/'Tests/AuthoredProjectileProductionTests.py')};exec((r/'Tests/AuthoredProjectileProductionTests.py').read_text().split('\nwith tempfile.TemporaryDirectory',1)[0],ns)
s=ns['s'].replace('public sealed class GameSession{','public sealed class GameSession{public NeutralProgression Progression=new NeutralProgression();')+'namespace Emberfall{public enum EquipmentMechanic{VenomSpread}public class NeutralProgression{public float MechanicRangeMultiplier(EquipmentMechanic m)=>1;public float MechanicPowerMultiplier(EquipmentMechanic m)=>1;}}';member=ns['member'];cast=member((r/'Assets/Scripts/Combat/PlayerController.Venom.cs').read_text(),'private void CastConcentratedVenom(')
s=s.replace('public int NewCastId()=>17;', 'public int NewCastId()=>17;public GameSession session;public EnemyController AimTarget;private CombatDamage Damage(float n)=>100*n;public void Cast(int rank,float range){CastConcentratedVenom(rank,range,new Color(0,1,0),41);}'+cast)
fixture=(r/'Tests/AuthoredProjectileProductionTests.cs').read_text().split('class Program{')[0]
fixture+='''class Program{static int n;static void C(bool b,string m){n++;if(!b)throw new Exception(m);}static object F(object p,string name)=>p.GetType().GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(p);static void Main(string[] args){Resources.Root=args[0];
for(int rank=1;rank<=3;rank++){foreach(var o in GameObject.All.ToArray())UnityEngine.Object.Destroy(o);GameObject.All.Clear();CombatSight.Wall=float.PositiveInfinity;
var hero=new GameObject().AddComponent<PlayerController>();hero.HeroClass=HeroClass.Ranger;hero.session=new GameSession{Player=hero,HasStarted=true};var target=new GameObject().AddComponent<EnemyController>();hero.AimTarget=target;hero.Cast(rank,2);
var all=GameObject.All.Where(o=>o.GetComponent<CombatProjectile>()!=null).ToArray();C(all.Length==1,"exactly one actual spawned projectile per cast");var p=all[0].GetComponent<CombatProjectile>();C(!(bool)F(p,"pierce")&&((CombatDamage)F(p,"explosionDamage")).Amount==0&&F(p,"volley")==null,"all ranks nonpiercing zero explosion no fan volley");C(Math.Abs(((CombatDamage)F(p,"damage")).Amount-100*ConcentratedVenomRules.DirectCoefficient(rank))<.001,"rank actual direct budget");C((float)F(p,"radius")==.14f&&ReferenceEquals(F(p,"concentratedTarget"),target)&&F(p,"homingTarget")==null,"narrow fixed intent no guaranteed homing");var body=(Transform)F(p,"visualBody");var trail=(TrailRenderer)F(p,"visualTrail");C(body.localScale.x<1&&body.localScale.z<1&&body.localScale.y>1,"concentrated narrow visual child only");C(trail.startWidth==.045f&&trail.time<=.1f&&trail.endWidth==0,"concentrated trail stays narrow and short");C((int)F(p,"castId")==41&&(int)F(p,"skillIndex")==0,"skill and cast registration identity");hero.AimTarget=new GameObject().AddComponent<EnemyController>();C(ReferenceEquals(F(p,"concentratedTarget"),target),"later selection cannot retarget in-flight arrow");}
Console.WriteLine("PASS "+n+" actual cast/factory checks; managed Unity boundaries");}}
'''
with tempfile.TemporaryDirectory(prefix='venom-launch-') as t:
 p=Path(t);(p/'Stubs.cs').write_text(s);(p/'Projectile.cs').write_text(ns['projectile']);(p/'Test.cs').write_text(fixture)
 for f in ['Combat/ConcentratedVenomRules','Combat/AuthoredProjectileMeshes','Combat/AuthoredActorMeshes','Combat/VisualMeshRecipes','Combat/AnchoredImpactMesh','Combat/CombatVisualLease','Core/CombatVisualBudget','Core/CastFirstHitReceipt']:(p/(Path(f).name+'.cs')).write_text((r/'Assets/Scripts'/(f+'.cs')).read_text())
 (p/'Test.csproj').write_text('<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><OutputType>Exe</OutputType><NoWarn>0649;0414</NoWarn></PropertyGroup></Project>');(p/'NuGet.Config').write_text('<configuration><packageSources><clear/></packageSources></configuration>');env=dict(os.environ,DOTNET_CLI_HOME=str(p/'cli'),DOTNET_NOLOGO='1')
 def run(expected=None):
  subprocess.run([sys.argv[1],'build',str(p/'Test.csproj'),'--configfile',str(p/'NuGet.Config'),'-v:q'],env=env,check=True);out=subprocess.run([sys.argv[1],str(p/'bin/Debug/net8.0/Test.dll'),str(r/'Assets/Resources')],env=env,capture_output=True,text=True);print(out.stdout+out.stderr)
  if expected:assert out.returncode and expected in out.stdout+out.stderr
  else:out.check_returncode()
 run();(p/'Stubs.cs').write_text(s.replace('arrow:true, size:1f','piercing:true, arrow:true, size:1f'));run('all ranks nonpiercing zero explosion no fan volley');print('PASS compiled piercing regression rejected')
