using System;using System.IO;using System.Linq;using System.Collections.Generic;using Emberfall;
namespace Emberfall{
public enum ExpeditionModeFailure{PlayerDefeated}public enum RoomFailureReason{Death}public enum SoundCue{Death,Loot}public static class GameAudio{public static void Play(SoundCue c){}}
public class FakeRun{public void Fail(object x){}}public class FakeChoice{public void Cancel(){}}
public class GroundLootPickup{public bool Retired;public void Retire(){Retired=true;}}
public partial class GameSession{
 // These death/receipt cases are ordinary runs; practice isolation has its own suite.
 // Any accidental practice path in an ordinary-run persistence test must fail loudly.
 public sealed class PracticeBoundary{public void PlayerDefeated(){throw new InvalidOperationException("ordinary loot fixture cannot record practice defeat");}}
 public PracticeBoundary PracticeRecord=>throw new InvalidOperationException("ordinary loot fixture cannot access practice record");
 public bool PracticeActive=>false;public void EndPractice(string reason){throw new InvalidOperationException("ordinary loot fixture cannot end practice");}
 public ProgressionService Progression;public bool IsDead,ChapterActive,DungeonSelectionOpen,Paused,uiBlocking;public FakeRun ModeRun,RoomChainRun;FakeChoice pendingRoomChoice=new FakeChoice();public string LastRunSummary,Notification;public int TimescaleUpdates,Transitions;
 class PendingLoot{public ItemData Item;public GroundLootPickup Pickup;public bool Collecting;}readonly Dictionary<string,PendingLoot> pendingLoot=new Dictionary<string,PendingLoot>();readonly HashSet<string> collectedGroundLoot=new HashSet<string>();
 public int PendingCount=>pendingLoot.Count;public GroundLootPickup Drop(ItemData i){var p=new GroundLootPickup();pendingLoot.Add(i.id,new PendingLoot{Item=i,Pickup=p});return p;}
 void FailChapter(string s){}string BuildRunSummary(bool won)=>"earned snapshot";void Notify(string s){Notification=s;}void LogSystem(string s){}void UpdateTimeScale(){TimescaleUpdates++;}bool ChangeZone(bool dungeon){Transitions++;return true;}
}}
class Program{
static int checks;static void Check(bool v,string s){checks++;if(!v)throw new Exception(s);}static ItemData Item(string id)=>new ItemData{id=id,name="earned drop",slot=ItemSlot.Armor,rarity=Rarity.Epic,level=2,health=10};
static int Count(ProgressionService p,string id)=>p.Profile.inventory.Count(x=>x.id==id)+p.Profile.pendingLoot.Count(x=>x.id==id)+p.Profile.recoveryLoot.Count(x=>x.id==id);
static ProgressionService New(string root){var p=new ProgressionService(Path.Combine(root,Guid.NewGuid().ToString("N")));Check(p.CreateNewSlot(HeroClass.Ranger),"create actual save");return p;}
static void Main(string[]args){foreach(bool full in new[]{false,true}){
 var p=New(args[0]);if(full){while(p.Profile.inventory.Count<ProgressionService.InventoryCapacity)p.Profile.inventory.Add(Item("bag"+p.Profile.inventory.Count));while(p.Profile.pendingLoot.Count<ProgressionService.PendingLootCapacity)p.Profile.pendingLoot.Add(Item("mail"+p.Profile.pendingLoot.Count));}p.Profile.gold+=17;p.Save();int gold=p.Profile.gold;var game=new GameSession{Progression=p};var drop=Item("deathdrop");var pickup=game.Drop(drop);game.OnPlayerDied();
 Check(Count(p,drop.id)==1&&game.PendingCount==0&&pickup.Retired,"death committed uncollected identity before returning");Check(game.IsDead&&game.LastRunSummary=="earned snapshot"&&p.Profile.gold==gold,"PR36 dead state earned summary and gold retained");string disk=File.ReadAllText(p.SaveFilePath);game.OnPlayerDied();Check(File.ReadAllText(p.SaveFilePath)==disk&&Count(p,drop.id)==1,"repeated death cannot grant again");
 Check(p.LoadSlot(p.CurrentSlotId)&&Count(p,drop.id)==1,"crash-like reopen of actual file retains identity without Respawn");game.Respawn();Check(!game.IsDead&&game.Transitions==1&&Count(p,drop.id)==1,"actual Respawn after death preservation does not duplicate");
 var reopened=new GameSession{Progression=p};var stale=reopened.Drop(drop);reopened.OnPlayerDied();Check(Count(p,drop.id)==1&&reopened.PendingCount==0&&stale.Retired,"stale same identity after reload deduplicates into durable bags");
 }
 {var p=New(args[0]);var game=new GameSession{Progression=p};var drop=Item("retrydrop");var pickup=game.Drop(drop);string disk=File.ReadAllText(p.SaveFilePath),backup=File.ReadAllText(p.SaveFilePath+".bak");File.Copy(p.SaveFilePath,p.SaveFilePath+".tmp");game.OnPlayerDied();Check(game.IsDead&&game.PendingCount==1&&!pickup.Retired&&Count(p,drop.id)==0,"failed death write retains exact world item");Check(!string.IsNullOrEmpty(p.LastError)&&game.Notification==p.LastError,"death failure is visible");Check(File.ReadAllText(p.SaveFilePath)==disk&&File.ReadAllText(p.SaveFilePath+".bak")==backup,"failed death preserves actual primary and backup");game.Respawn();Check(game.IsDead&&game.Transitions==0&&game.PendingCount==1&&Count(p,drop.id)==0,"failed retry cannot change world or grant");File.Delete(p.SaveFilePath+".tmp");game.Respawn();Check(!game.IsDead&&game.PendingCount==0&&pickup.Retired&&Count(p,drop.id)==1,"actual Respawn retries retained identity once");game.Respawn();Check(Count(p,drop.id)==1&&game.Transitions==1,"repeated respawn has no duplicate grant");Check(p.LoadSlot(p.CurrentSlotId)&&Count(p,drop.id)==1,"successful retry survives reopen");}
 {var p=New(args[0]);var game=new GameSession{Progression=p};ItemData first=Item("partial-first"),second=Item("partial-second");var firstPickup=game.Drop(first);var secondPickup=game.Drop(second);bool blocked=false;p.Changed+=()=>{if(!blocked&&Count(p,first.id)==1){blocked=true;File.Copy(p.SaveFilePath,p.SaveFilePath+".tmp");}};
 game.OnPlayerDied();Check(Count(p,first.id)==1&&Count(p,second.id)==0&&game.PendingCount==1&&firstPickup.Retired&&!secondPickup.Retired,"partial write publishes only accepted first pickup");Check(game.IsDead&&!string.IsNullOrEmpty(p.LastError),"partial failure remains visible on death screen");File.Delete(p.SaveFilePath+".tmp");game.Respawn();Check(Count(p,first.id)==1&&Count(p,second.id)==1&&game.PendingCount==0&&secondPickup.Retired,"partial retry does not duplicate already committed first item");Check(p.LoadSlot(p.CurrentSlotId)&&Count(p,first.id)==1&&Count(p,second.id)==1,"both accepted partial identities survive actual reload");}
 Console.WriteLine(WorldLootReceiptTests.Run(args[0]));Console.WriteLine("PASS "+checks+" actual death/pending/Respawn adapters and service durable writes; scene/audio boundaries doubled, not Unity execution.");}
}
