// Construction executes the actual Hero, equipment, fashion and mesh recipe code.
// Managed hierarchy implements TRS/reparenting and deferred destruction; shaders/cloth
// simulation and color lookup are doubles. Relic clearance uses actual transformed vertices;
// weapon class/grip attachment uses real hierarchy/anchors, not a general triangle-intersection solver.
// This is static authored geometry, not animated collision/render proof.
using System;using System.Collections;using System.Collections.Generic;using System.Linq;using System.Reflection;using UnityEngine;using Emberfall;
namespace UnityEngine {
 public class Object {
  public static readonly List<Object> All=new List<Object>();public string name;public bool destroyed;static readonly HashSet<Object> pending=new HashSet<Object>();public Object(){All.Add(this);}
  public static void Destroy(Object o){if(o!=null&&!o.destroyed)pending.Add(o);}public static void Flush(){while(pending.Count>0){var o=pending.First();pending.Remove(o);if(o.destroyed)continue;if(o is GameObject g){foreach(var child in g.transform.children.ToArray())Destroy(child.gameObject);foreach(var c in g.components.ToArray()){GameObject.Call(c,"OnDestroy");c.destroyed=true;}g.transform.parent?.children.Remove(g.transform);}o.destroyed=true;}}
 }
 public class Component:Object {public GameObject gameObject;public Transform transform=>gameObject.transform;public T GetComponent<T>()where T:Component=>gameObject.GetComponent<T>();public T[] GetComponentsInChildren<T>(bool inactive)where T:Component=>gameObject.GetComponentsInChildren<T>(inactive);}
 public class MonoBehaviour:Component {}
 public class GameObject:Object {
  public bool activeSelf=true;public bool activeInHierarchy=>activeSelf&&!destroyed&&(transform.parent==null||transform.parent.gameObject.activeInHierarchy);public Transform transform;public readonly List<Component> components=new List<Component>();
  public GameObject(string n){name=n;transform=new Transform{gameObject=this};components.Add(transform);}public void SetActive(bool a){activeSelf=a;}
  public T AddComponent<T>()where T:Component,new(){var c=new T{gameObject=this};components.Add(c);Call(c,"Awake");return c;}public T GetComponent<T>()where T:Component=>components.OfType<T>().FirstOrDefault(c=>!c.destroyed);
  public T[] GetComponentsInChildren<T>(bool inactive)where T:Component{var list=new List<T>();if(!destroyed&&(inactive||activeInHierarchy))list.AddRange(components.OfType<T>().Where(c=>!c.destroyed));foreach(var child in transform.children.ToArray())list.AddRange(child.gameObject.GetComponentsInChildren<T>(inactive));return list.ToArray();}
  public static void Call(object o,string m)=>o.GetType().GetMethod(m,BindingFlags.Instance|BindingFlags.NonPublic)?.Invoke(o,null);
 }
 public class Transform:Component,IEnumerable<Transform> {
  public new string name=>gameObject.name;public Transform parent;public List<Transform> children=new List<Transform>();public Vector3 localPosition,localScale=Vector3.one;public Quaternion localRotation=Quaternion.identity;
  public Vector3 position{get=>TransformPoint(Vector3.zero);set=>localPosition=parent==null?value:parent.InverseTransformPoint(value);}public Quaternion rotation=>parent==null?localRotation:parent.rotation*localRotation;
  public Vector3 TransformPoint(Vector3 p){var q=localPosition+localRotation*Vector3.Scale(p,localScale);return parent==null?q:parent.TransformPoint(q);}public Vector3 InverseTransformPoint(Vector3 p){if(parent!=null)p=parent.InverseTransformPoint(p);p=Quaternion.Inverse(localRotation)*(p-localPosition);return new Vector3(p.x/localScale.x,p.y/localScale.y,p.z/localScale.z);}
  public void SetParent(Transform p,bool world){Vector3 at=position;Quaternion rot=rotation;parent?.children.Remove(this);parent=p;p?.children.Add(this);if(world){position=at;localRotation=p==null?rot:Quaternion.Inverse(p.rotation)*rot;}}
  public Transform Find(string n)=>children.FirstOrDefault(c=>c.name==n&&!c.gameObject.destroyed);public IEnumerator<Transform> GetEnumerator()=>children.GetEnumerator();IEnumerator IEnumerable.GetEnumerator()=>GetEnumerator();
 }
 public struct Vector3 {
  public float x,y,z;public Vector3(float a,float b,float c){x=a;y=b;z=c;}public static Vector3 zero=>new Vector3();public static Vector3 one=>new Vector3(1,1,1);public static Vector3 up=>new Vector3(0,1,0);public static Vector3 down=>new Vector3(0,-1,0);public static Vector3 right=>new Vector3(1,0,0);public static Vector3 left=>new Vector3(-1,0,0);public static Vector3 forward=>new Vector3(0,0,1);public static Vector3 back=>new Vector3(0,0,-1);public float sqrMagnitude=>x*x+y*y+z*z;public float magnitude=>(float)Math.Sqrt(x*x+y*y+z*z);public Vector3 normalized=>magnitude>0?this/magnitude:zero;
  public static Vector3 operator+(Vector3 a,Vector3 b)=>new Vector3(a.x+b.x,a.y+b.y,a.z+b.z);public static Vector3 operator-(Vector3 a,Vector3 b)=>new Vector3(a.x-b.x,a.y-b.y,a.z-b.z);public static Vector3 operator-(Vector3 a)=>a*-1;public static Vector3 operator*(Vector3 a,float b)=>new Vector3(a.x*b,a.y*b,a.z*b);public static Vector3 operator*(float b,Vector3 a)=>a*b;public static Vector3 operator/(Vector3 a,float b)=>a*(1/b);public static Vector3 Scale(Vector3 a,Vector3 b)=>new Vector3(a.x*b.x,a.y*b.y,a.z*b.z);public static Vector3 Cross(Vector3 a,Vector3 b)=>new Vector3(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x);public override string ToString()=>$"({x:F3},{y:F3},{z:F3})";
 }
 public struct Vector2{public float x,y;public Vector2(float a,float b){x=a;y=b;}}
 public struct Quaternion {internal System.Numerics.Quaternion q;public static Quaternion identity=>new Quaternion{q=System.Numerics.Quaternion.Identity};public static Quaternion Euler(float x,float y,float z)=>new Quaternion{q=System.Numerics.Quaternion.CreateFromYawPitchRoll(y*Mathf.PI/180,x*Mathf.PI/180,z*Mathf.PI/180)};public static Quaternion Inverse(Quaternion a)=>new Quaternion{q=System.Numerics.Quaternion.Inverse(a.q)};public static Quaternion operator*(Quaternion a,Quaternion b)=>new Quaternion{q=a.q*b.q};public static Vector3 operator*(Quaternion a,Vector3 p){var v=System.Numerics.Vector3.Transform(new System.Numerics.Vector3(p.x,p.y,p.z),a.q);return new Vector3(v.X,v.Y,v.Z);}}
 public struct Color{public float r,g,b,a;public Color(float r,float g,float b,float a=1){this.r=r;this.g=g;this.b=b;this.a=a;}public static Color black=>new Color(0,0,0);public static Color white=>new Color(1,1,1);public static Color operator*(Color c,float f)=>new Color(c.r*f,c.g*f,c.b*f,c.a*f);public static Color Lerp(Color a,Color b,float t)=>new Color(a.r+(b.r-a.r)*t,a.g+(b.g-a.g)*t,a.b+(b.b-a.b)*t,a.a+(b.a-a.a)*t);}
 public class Shader {public static Shader Find(string n)=>new Shader();}
 public class Material:Object {public Color color;public bool enableInstancing;public Material(Shader s){}public bool HasProperty(string n)=>true;public void SetFloat(string n,float v){}public void EnableKeyword(string s){}public void SetColor(string n,Color c){}}
 public class Mesh:Object {public Vector3[] vertices,normals;public Vector2[] uv;public int[] triangles;public void RecalculateNormals(){}public void RecalculateBounds(){}}
 public class MeshFilter:Component {public Mesh sharedMesh;}
 public static class Application{public static bool isMobilePlatform;}
 public class TrailRenderer:Renderer{public float time,startWidth,endWidth,minVertexDistance;public int numCapVertices,numCornerVertices,Clears;public bool emitting;public Color startColor,endColor;public void Clear(){Clears++;}}
 public class Renderer:Component {public bool enabled=true,receiveShadows;public Material sharedMaterial;public Rendering.ShadowCastingMode shadowCastingMode;}
 public class MeshRenderer:Renderer{}public class LineRenderer:Renderer {public bool useWorldSpace;public int positionCount;public float startWidth,endWidth;public Vector3[] points=new Vector3[3];public void SetPosition(int i,Vector3 p){points[i]=p;}}
 public enum PrimitiveType{Cube,Sphere,Capsule,Cylinder,Quad}public enum RuntimeInitializeLoadType{SubsystemRegistration}public class RuntimeInitializeOnLoadMethodAttribute:Attribute{public RuntimeInitializeOnLoadMethodAttribute(RuntimeInitializeLoadType t){}}
 public static class Random{public static float value=>.5f;}public static class Time{public static float deltaTime=.016f;}
 public static class Mathf{public static float Clamp01(float x)=>Math.Max(0,Math.Min(1,x));public const float PI=(float)Math.PI,Deg2Rad=PI/180;public static float Sin(float x)=>(float)Math.Sin(x);public static float Cos(float x)=>(float)Math.Cos(x);public static float Abs(float x)=>Math.Abs(x);public static int Min(int x,int y)=>Math.Min(x,y);public static int Clamp(int x,int a,int b)=>Math.Max(a,Math.Min(b,x));public static float Clamp(float x,float a,float b)=>Math.Max(a,Math.Min(b,x));public static float Repeat(float x,float y)=>x-(float)Math.Floor(x/y)*y;}
}
namespace UnityEngine.Rendering{public enum ShadowCastingMode{On,Off}}
namespace Emberfall {public static class EffectPreferences{public static bool ReducedEffects;}
 public class TailoredCloth:MonoBehaviour{public HeroClass Profile;public void Initialize(Material m,HeroClass hero=HeroClass.Vanguard){Profile=hero;}}public class LargeBossRig:MonoBehaviour{}public class EnemyController:MonoBehaviour{}
 public static class ProgressionService{public const int MaximumLevel=100,MaximumUpgrade=10;}
 public static class GameBalance {public static Color ClassColor(HeroClass h)=>new Color(.2f+(int)h*.12f,.6f,.8f);public static Color RarityColor(Rarity r)=>new Color(.4f+(int)r*.15f,.7f,.3f);}
}
public static class EquipmentCompositionProductionTests {
 static int checks;static void Check(bool ok,string text){checks++;if(!ok)throw new Exception(text);}static int Live<T>()where T:UnityEngine.Object=>UnityEngine.Object.All.OfType<T>().Count(x=>!x.destroyed);
 static Transform Find(CombatModel m,string name)=>m.GetComponentsInChildren<Transform>(true).Single(x=>x.name==name&&!x.gameObject.destroyed);
 static Vector3[] Vertices(Transform t,Transform space)=>t.GetComponentsInChildren<MeshFilter>(false).SelectMany(f=>f.sharedMesh.vertices.Select(v=>space.InverseTransformPoint(f.transform.TransformPoint(v)))).ToArray();
 static void ResetMeshes(){typeof(CostumeMeshLibrary).GetMethod("Reset",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,null);typeof(ProceduralVisuals).GetMethod("ResetCache",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,null);UnityEngine.Object.Flush();}
 public static void Main(){
 var parent=new GameObject("trs-check");parent.transform.localPosition=new Vector3(2,3,4);parent.transform.localRotation=Quaternion.Euler(0,90,0);parent.transform.localScale=new Vector3(2,2,2);var child=new GameObject("trs-child");child.transform.SetParent(parent.transform,false);child.transform.localPosition=new Vector3(0,0,1);Check((child.transform.position-new Vector3(4,3,4)).magnitude<.0001f,"hierarchical TRS sanity");var before=child.transform.position;child.transform.SetParent(null,true);Check((child.transform.position-before).magnitude<.0001f,"world-preserving reparent sanity");UnityEngine.Object.Destroy(child);UnityEngine.Object.Destroy(parent);UnityEngine.Object.Flush();
 foreach(HeroClass hero in Enum.GetValues(typeof(HeroClass)))foreach(int upgrade in new[]{0,3,7,10})foreach(bool fashionFirst in new[]{false,true}){
 var host=new GameObject("hero");var model=CombatModel.Hero(host.transform,hero);Check(model.GetComponentsInChildren<TailoredCloth>(true).Single().Profile==hero,"actual Hero factory passes class to rear silhouette before EnhanceHero");UnityEngine.Object.Flush();var gear=Enum.GetValues(typeof(ItemSlot)).Cast<ItemSlot>().Select(slot=>new ItemData{id=slot.ToString(),slot=slot,rarity=Rarity.Legendary,level=100,upgradeLevel=upgrade}).ToArray();var wings=new FashionData{id="max wings",slot=FashionSlot.Wings,rarity=Rarity.Legendary};var weapon=new FashionData{id="max weapon",slot=FashionSlot.Weapon,rarity=Rarity.Legendary};
 if(fashionFirst)model.ApplyFashion(wings,weapon);model.ApplyEquipment(gear[0],gear[1],gear[2]);model.ApplyFashion(wings,weapon);UnityEngine.Object.Flush();
 Check(new EquipmentAppearance(gear[0]).Tier==4,"fixture really selects T4");var relic=Find(model,"Equipped Relic");var rv=Vertices(relic,model.transform);Check(rv.Length>0,"actual relic has mesh vertices");Check(rv.All(v=>Math.Abs(v.x)<.245f&&v.y>.65f&&v.y<1.045f&&v.z>=.39f-.0001f&&v.z<.535f),"actual relic vertices preserve face/chest/grip/back envelope");
 Check(relic.parent.name=="Spine"&&Math.Abs(relic.localPosition.y+1.12f)<.0001f,"relic attached to compensated spine origin");var equip=Find(model,"Equipped Weapon");var fw=Find(model,"Fashion Weapon");Check(equip.parent==fw.parent,"fashion and equipped weapon share the class wrist anchor");string costume=hero==HeroClass.Vanguard?"Raised breastplate":hero==HeroClass.Arcanist?"Equipped robe skirt":hero==HeroClass.Ranger?"Asymmetric leather chest wrap":"Spirit ritual bib";Check(Find(model,costume).gameObject.activeInHierarchy,"equipped armor preserves actual class identity geometry");Check(Find(model,"Fashion Wings").parent.name=="Spine","back fashion follows spine");
 var all=model.GetComponentsInChildren<MeshFilter>(false);Check(all.Length>50&&all.Length<250,"bounded combined production part count");foreach(var f in all){Check(f.sharedMesh!=null&&!f.sharedMesh.destroyed&&f.GetComponent<Renderer>().sharedMaterial!=null&&!f.GetComponent<Renderer>().sharedMaterial.destroyed,"live mesh/material for visible piece");Check(f.sharedMesh.vertices.All(v=>float.IsFinite(v.x)&&float.IsFinite(v.y)&&float.IsFinite(v.z)),"finite actual recipe vertices");}
 if(hero==HeroClass.Arcanist||hero==HeroClass.Summoner){var shaft=Find(model,"Inlaid staff");var sv=Vertices(shaft,equip.parent);Check(Math.Abs(sv.Min(v=>v.y)+.94f)<.0001f,"T4 staff lower end stays at authored safe bound");Check(Vertices(shaft,model.transform).Min(v=>v.y)>.09f,"staff bottom clears ground in constructed rest rig");Check(equip.parent.name=="Staff Wrist","caster weapon identity retained");}
 else if(hero==HeroClass.Vanguard){Check(Find(model,"Tiered blade").parent==equip,"actual sword blade belongs to sword equipment");Vector3 tip;Check(model.TryGetWeaponVisualAnchor(WeaponVisualAnchor.SwordTip,out tip)&&Vertices(Find(model,"Tiered blade"),equip.parent).Max(v=>v.y)>1.7f,"T4 blade agrees with real tip anchor family");}
 else {Check(equip.parent.name=="Bow","ranger retains bow class rig");Check(Find(model,"Drawn Bowstring").GetComponent<LineRenderer>().points[0].y>.8f,"T4 bowstring uses upgraded real tips");}
 int objects=Live<GameObject>(),meshes=Live<Mesh>(),materials=Live<Material>();for(int i=0;i<5;i++){model.ApplyEquipment(gear[0],gear[1],gear[2]);model.ApplyFashion(wings,weapon);}UnityEngine.Object.Flush();Check(Live<GameObject>()==objects&&Live<Mesh>()==meshes&&Live<Material>()==materials,"identical composition is allocation-free");
 for(int cycle=0;cycle<4;cycle++){var old=Find(model,"Equipped Relic");model.ApplyEquipment(null,null,null);Check(!old.gameObject.activeSelf,"unequip hides old geometry before deferred destruction");model.ApplyFashion(null,null);UnityEngine.Object.Flush();model.ApplyEquipment(gear[0],gear[1],gear[2]);model.ApplyFashion(wings,weapon);UnityEngine.Object.Flush();Check(Live<GameObject>()==objects&&Live<Mesh>()==meshes&&Live<Material>()==materials,"swap cycles keep resources bounded");}
 UnityEngine.Object.Destroy(host);UnityEngine.Object.Flush();Check(Live<GameObject>()==0&&Live<Material>()==0,"model disposal releases hierarchy and own palette");Check(UnityEngine.Object.All.OfType<Mesh>().Where(m=>!m.destroyed).All(m=>m.name.StartsWith("Shared costume")||m.name.StartsWith("Emberfall shared")),"only shared shape caches survive model disposal");ResetMeshes();Check(Live<Mesh>()==0,"shared cache reset releases all remaining meshes");
 }
 Console.WriteLine("PASS: "+checks+" production composition assertions; 4 heroes x 4 upgrade ranks x 2 equip orders, T4 + highest fashion. Static TRS/resources only, no Unity animation or GPU validation.");
 }
}
