using System;using System.Linq;using System.Reflection;using Emberfall;using UnityEngine;
class FilledVfxPoolProductionTests
{
 static int checks;static readonly BindingFlags I=BindingFlags.Instance|BindingFlags.NonPublic,S=BindingFlags.Static|BindingFlags.NonPublic;
 static void Check(bool b,string m){checks++;if(!b)throw new Exception(m);}
 static object Field(object o,string key)=>o.GetType().GetField(key,I).GetValue(o);
 static void Reset(){foreach(var o in GameObject.All.ToArray())UnityEngine.Object.Destroy(o);GameObject.All.Clear();typeof(FilledSkillVfx).GetMethod("ResetAssets",S).Invoke(null,null);typeof(CombatVisualLease).GetMethod("Reset",S).Invoke(null,null);}
 static FilledSkillVfx Cast(PlayerController h,FilledVfxKind k=FilledVfxKind.Ice,CombatVisualPriority priority=CombatVisualPriority.ActionBody){FilledSkillVfx.Impact(h,Vector3.zero,3,k,new Color(1,.4f,.2f,.8f),priority,priority==CombatVisualPriority.Finale?77:0);return GameObject.All.Where(o=>o.activeInHierarchy&&!o.Destroyed).Select(o=>o.GetComponent<FilledSkillVfx>()).LastOrDefault(f=>f!=null);}
 static void Tick(FilledSkillVfx fx,float dt){Time.deltaTime=Time.unscaledDeltaTime=dt;fx.gameObject.Call("Update");}
 static PlayerController Hero(){var h=new GameObject("hero").AddComponent<PlayerController>();GameSession.Instance=new GameSession{Player=h,HasStarted=true};return h;}
 static GameObject[] Children(FilledSkillVfx fx)=>GameObject.All.Where(o=>o.transform.parent==fx.transform&&!o.Destroyed).ToArray();
 static void Clean(FilledSkillVfx fx){Check(!fx.gameObject.activeSelf,"retired root hidden");foreach(var name in new[]{"owner","session","lease"})Check(Field(fx,name)==null,"retire clears "+name);foreach(var name in new[]{"age","life","size","terminalAge"})Check((float)Field(fx,name)==0,"retire clears "+name);Check((int)Field(fx,"epoch")==0&&(int)Field(fx,"finaleCast")==0&&!(bool)Field(fx,"confirmedFinale"),"retire clears epoch/finale");Check(fx.transform.parent==null,"retire clears parent");var lease=fx.GetComponent<CombatVisualLease>();Check(Field(lease,"ticket")==null&&Field(lease,"retireAction")==null&&!(bool)Field(lease,"initialized")&&(CombatVisualPriority)Field(lease,"priority")==CombatVisualPriority.Decoration,"retire clears lease priority and callbacks");foreach(var o in Children(fx)){var renderer=o.GetComponent<MeshRenderer>();Check(!o.activeSelf&&!renderer.enabled&&renderer.Opacity==0&&renderer.TintAlpha==0,"retire clears visual alpha and activation");Check(renderer.sharedMaterial==null&&o.GetComponent<MeshFilter>().sharedMesh==null,"retire detaches shared and clipped mesh bindings");}}
 static void Main(string[] args){Resources.Root=args[0];Reset();var h=Hero();Application.isMobilePlatform=false;EffectPreferences.ReducedEffects=false;CombatSight.Wall=.4f;
 // Explicitly deferred Awake: the managed GameObject stub never calls it.
 EffectPreferences.ReducedEffects=true;
 for(int n=0;n<12;n++)CombatVisualLease.Attach(new GameObject("occupied"),CombatVisualPriority.Finale);
 Check(Cast(h,FilledVfxKind.Ice,CombatVisualPriority.Decoration)==null,"inactive first rental is rejected before Awake");
 var rejected=GameObject.All.Select(o=>o.GetComponent<FilledSkillVfx>()).First(f=>f!=null);
 Check(Field(rejected,"block")!=null,"rejection cleanup initializes native property block before Awake");Clean(rejected);
 Reset();h=Hero();EffectPreferences.ReducedEffects=false;
 var neverActive=new GameObject("never active");neverActive.SetActive(false);var raw=neverActive.AddComponent<FilledSkillVfx>();raw.Retire();Check(Field(raw,"block")!=null,"direct pre-Awake cleanup initializes block");Reset();h=Hero();
 // Warm all slots once, then reuse through several quality levels, priorities and owners.
 var first=Cast(h);var shared=(Mesh)typeof(FilledSkillVfx).GetField("rupture",S).GetValue(null);var owned=Children(first).Select(o=>o.GetComponent<MeshFilter>().sharedMesh).Where(m=>m!=null&&m.name.Contains("clipped")).ToArray();first.Retire();Clean(first);Check(!shared.Destroyed,"return does not destroy shared geometry");Cast(h,FilledVfxKind.Fire,CombatVisualPriority.Finale).Retire();Cast(h,FilledVfxKind.Ice,CombatVisualPriority.Finale).Retire();int warm=GameObject.All.Count;
 for(int n=0;n<90;n++){Application.isMobilePlatform=n%3!=0;EffectPreferences.ReducedEffects=n%3==2;var fx=Cast(h,n%2==0?FilledVfxKind.Ice:FilledVfxKind.Fire,n%4==0?CombatVisualPriority.Finale:CombatVisualPriority.ActionBody);Check(object.ReferenceEquals(fx,first),"warm cycle reuses same root");Check((float)Field(fx,"age")==0&&Field(fx,"owner")==h&&Field(fx,"session")==GameSession.Instance,"rent initializes new owner session and time");int cap=EffectPreferences.ReducedEffects?7:Application.isMobilePlatform?10:14;Check(Children(fx).Count(o=>o.activeInHierarchy)<=cap,"reuse honors lower quality active-part cap");var meshes=Children(fx).Where(o=>o.activeInHierarchy).Select(o=>o.GetComponent<MeshFilter>().sharedMesh).Take(3).ToArray();GameSession.Instance.InputBlocked=true;Tick(fx,.1f);Check((float)Field(fx,"age")==0,"pooled effect pauses");GameSession.Instance.InputBlocked=false;Tick(fx,2);Clean(fx);Check(meshes.All(m=>m.Destroyed),"return destroys each cast clipped geometry");Check(!shared.Destroyed,"cycle keeps immutable source");Check(CombatVisualLease.Active==0,"return releases priority lease");Check(GameObject.All.Count==warm,"warm cycles do not grow roots or renderer objects");}
 // Sustained rain replays certified geometry until its spatial/quality contract changes.
 var rain=FilledSkillVfx.ArrowRain(h,Vector3.zero,3,new Color(1,.7f,.3f));
 var rainFx=GameObject.All.Where(o=>o.activeInHierarchy&&!o.Destroyed).Select(o=>o.GetComponent<FilledSkillVfx>()).Last(f=>f!=null);
 var rainMeshes=Children(rainFx).Where(o=>o.activeInHierarchy).Select(o=>o.GetComponent<MeshFilter>().sharedMesh).ToArray();
 int clipCalls=CombatSight.FootprintCalls,objects=GameObject.All.Count;
 for(int beat=0;beat<16;beat++){rain.ArrowBeat(Vector3.zero,3,false);Check(CombatSight.FootprintCalls==clipCalls,"repeated rain does not repeat cover clipping");Check(GameObject.All.Count==objects&&rainMeshes.All(m=>!m.Destroyed),"repeated rain retains mesh and renderer allocation");}
 WorldTraversal.Revision++;rain.ArrowBeat(Vector3.zero,3,false);Check(CombatSight.FootprintCalls>clipCalls&&rainMeshes.Any(m=>m.Destroyed),"changed cover rebuilds certified rain geometry");
 clipCalls=CombatSight.FootprintCalls;rain.ArrowBeat(new Vector3(-1,0,0),3,false);Check(CombatSight.FootprintCalls>clipCalls,"moved rain rebuilds geometry");
 clipCalls=CombatSight.FootprintCalls;rain.ArrowBeat(new Vector3(-1,0,0),3,true);Check(CombatSight.FootprintCalls>clipCalls,"final arrow retains distinct rebuilt silhouette");rain.Retire();Clean(rainFx);
 // A new session with the same hero cannot inherit the previous visual lifetime.
 var old=Cast(h);GameSession.Instance=new GameSession{Player=h,HasStarted=true};Tick(old,.01f);Clean(old);
 var secondHero=Hero();var reused=Cast(secondHero,FilledVfxKind.Fire);Check(reused==first&&Field(reused,"owner")==secondHero,"cross-owner reuse is fresh");secondHero.CombatEpoch++;Tick(reused,.01f);Clean(reused);
 // Fill and preempt priority leases; rejected rentals must also return cleanly.
 Application.isMobilePlatform=true;EffectPreferences.ReducedEffects=true;for(int n=0;n<12;n++)Cast(secondHero,FilledVfxKind.Fire,CombatVisualPriority.Finale);Check(CombatVisualLease.Active==12,"pool does not bypass global cap");for(int n=0;n<25;n++)Cast(secondHero,FilledVfxKind.Ice,CombatVisualPriority.Decoration);Check(CombatVisualLease.Active==12,"rejected rentals preserve global cap");foreach(var o in GameObject.All.Where(o=>o.activeInHierarchy).ToArray()){var fx=o.GetComponent<FilledSkillVfx>();if(fx!=null)fx.Retire();}Check(CombatVisualLease.Active==0,"all priority slots released");int cached=(int)typeof(FilledSkillVfx).GetField("idle",S).GetValue(null).GetType().GetProperty("Count").GetValue(typeof(FilledSkillVfx).GetField("idle",S).GetValue(null));Check(cached<=8,"inactive retention bounded to eight roots");
 typeof(FilledSkillVfx).GetMethod("ResetAssets",S).Invoke(null,null);Check(shared.Destroyed,"cache reset owns shared mesh destruction");Check(GameObject.All.Where(o=>o.GetComponent<FilledSkillVfx>()!=null).All(o=>o.Destroyed),"subsystem reset destroys pooled and active roots");Reset();Console.WriteLine("PASS "+checks+" actual loaded pooled VFX ownership/reset/cap/warm-loop assertions; managed, not engine allocation/FPS.");}
}
