using System;using System.Linq;using System.IO;using System.Collections.Generic;using System.Reflection;using System.Security.Cryptography;using System.Text;using UnityEngine;using Emberfall;
class FixedSceneryEnabledIntegrationTests
{
 static int checks,factoryRuns;static void Check(bool ok,string why){checks++;if(!ok)throw new Exception(why);}
 static void Static(Type t,string method)=>t.GetMethod(method,BindingFlags.NonPublic|BindingFlags.Static).Invoke(null,null);
 static object Field(object o,string name)=>o.GetType().GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);
 static List<CameraOcclusionSurface> Registry=>(List<CameraOcclusionSurface>)typeof(CameraOcclusionSurface).GetField("surfaces",BindingFlags.NonPublic|BindingFlags.Static).GetValue(null);
 static int Faded=>(int)typeof(CameraOcclusionSurface).GetField("fadedCount",BindingFlags.NonPublic|BindingFlags.Static).GetValue(null);
 static string V(Vector3 v)=>v.x.ToString("R")+","+v.y.ToString("R")+","+v.z.ToString("R");
 static string PathOf(Transform t)=>t.parent==null?t.name:PathOf(t.parent)+"/"+t.name;
 static string Pose(Transform t)=>V(t.localPosition)+"|"+V(t.localScale)+"|"+V(t.localRotation*Vector3.up)+"|"+V(t.localRotation*Vector3.forward);
 static string Nav()=>string.Join(";",WorldTraversal.boxes.Select(x=>V(x.p)+":"+x.size.x.ToString("R")+","+x.size.y.ToString("R")))+"/"+string.Join(";",WorldTraversal.circles.Select(x=>V(x.p)+":"+x.radius.ToString("R")));
 static string Marks()=>string.Join(";",Registry.Select(x=>PathOf(x.transform)+"|"+(Field(x,"group") is BuildingOcclusionGroup g?PathOf(g.transform):"ungrouped")));
 static string ColorKey(Material m)=>m==null?"null":m.color.r+","+m.color.g+","+m.color.b+","+m.color.a+"|"+m.GetFloat("_Glossiness")+"|"+m.GetFloat("_Metallic");
 static readonly Dictionary<Mesh,string> digests=new Dictionary<Mesh,string>();
 static string MeshKey(Mesh m){if(m==null)return "line";if(!digests.TryGetValue(m,out var result)){var text=string.Join(";",m.vertices.Select(V))+"/"+string.Join(",",m.triangles);result=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(text)));digests[m]=result;}return result;}
 // Independent expected dispatch and exact multiplicities: not computed by the adapter's Key method.
 static readonly Dictionary<string,string> keys=new Dictionary<string,string>{
 {"Column base","ColumnBase"},{"Column","FlutedColumn"},{"Capital","Capital"},{"Capital bevel collar","Collar"},{"Column band","ColumnBand"},{"Gate plinth","GatePlinth"},{"Gate frame","GateFrame"},
 {"Pitched workshop roof module","RoofTiles"},{"Workshop projecting eave","Eave"},{"Workshop ridge cap","Ridge"},{"Kiln chimney cap","ChimneyCap"},{"Merchant stocked shelf","Shelf"},{"Forged anvil face","Anvil"},{"Anvil stump","Stump"},{"Exchange lectern","Lectern"},{"Observatory circular dais","ObservatoryDais"},
 {"NPC tunic","NpcTunic"},{"NPC sleeve","NpcSleeve"},{"NPC boots","NpcBoot"},{"NPC head","NpcHead"},{"Merchant cap","MerchantCap"},{"Smith leather apron","Apron"},
 {"STAR CORE plinth","FacilityBase"},{"APPRENTICE plinth","FacilityBase"},{"CODEX plinth","FacilityBase"},{"CLASS TRIAL plinth","FacilityBase"},
 {"STAR CORE fixed crest","CoreCrest"},{"APPRENTICE fixed crest","ApprenticeCrest"},{"CODEX fixed crest","CodexCrest"},{"CLASS TRIAL fixed crest","TrialCrest"}};
 static readonly string npc="NpcTunic:3,NpcHead:3,NpcBoot:6,NpcSleeve:6,MerchantCap:1,Shelf:2,Apron:1,Stump:1,Anvil:1,Lectern:1";
 static readonly string npcTown="NpcTunic:2,NpcHead:2,NpcBoot:4,NpcSleeve:4,MerchantCap:1,Shelf:2,Apron:1,Stump:1,Anvil:1";
 static readonly string[] expected={"ColumnBase:1,FlutedColumn:1,Capital:1,Collar:1,ColumnBand:1","GatePlinth:1,GateFrame:1","RoofTiles:12,Eave:12,Ridge:6,ChimneyCap:6,GatePlinth:1,GateFrame:1,"+npcTown,"ObservatoryDais:1,GatePlinth:1,GateFrame:1,"+npcTown,"FacilityBase:4,CoreCrest:1,ApprenticeCrest:1,CodexCrest:1,TrialCrest:1",npcTown};
 static Dictionary<string,int> Counts(int group)=>expected[group].Split(',').Select(x=>x.Split(':')).ToDictionary(x=>x[0],x=>int.Parse(x[1]));
 class Part{public string Name,Key,Mesh,Pose,Materials,Parent;public bool Authored;}
 class Snapshot{public string Nav,Marks,Physics,Dynamic;public Dictionary<string,Part> Parts;}
 static GameObject Build(int i,bool enabled,string key=null,string mode=null){Static(typeof(AuthoredFixedScenery),"Reset");UnityEngine.Object.Flush();Resources.FaultKey=key;Resources.FaultMode=mode;Resources.Loads.Clear();AuthoredFixedScenery.Enabled=enabled;WorldTraversal.Reset(ZoneKind.Wilderness);var root=new GameObject("sample");WorldBuilder.FixedSample(root.transform,root.AddComponent<WorldResources>(),i);factoryRuns++;return root;}
 static void Dispose(GameObject root){CameraOcclusionSurface.RestoreAll();root.SetActive(false);UnityEngine.Object.Destroy(root);UnityEngine.Object.Flush();Check(Registry.Count==0&&Faded==0,"factory teardown releases all actual occlusion state");}
 static Snapshot Capture(GameObject root){var parts=new Dictionary<string,Part>();var names=new Dictionary<string,int>();foreach(var r in root.GetComponentsInChildren<Renderer>(true)){string name=r.transform.name;int index=names.TryGetValue(name,out var n)?n:0;names[name]=index+1;var mesh=r.GetComponent<MeshFilter>()?.sharedMesh;keys.TryGetValue(name,out var key);parts[name+"#"+index]=new Part{Name=name,Key=key,Mesh=MeshKey(mesh),Pose=Pose(r.transform),Materials=string.Join("/",r.sharedMaterials.Select(ColorKey)),Parent=PathOf(r.transform.parent),Authored=mesh!=null&&mesh.name.StartsWith("Blender fixed scenery ")};}return new Snapshot{Parts=parts,Nav=Nav(),Marks=Marks(),Physics=string.Join(";",root.GetComponentsInChildren<Collider>(true).Select(x=>PathOf(x.transform)))+"/"+string.Join(";",root.GetComponentsInChildren<Rigidbody>(true).Select(x=>PathOf(x.transform)))};}
 static void Advance(GameObject root){foreach(var m in root.GetComponentsInChildren<WorldMotion>(true))GameObject.Call(m,"Start");foreach(float step in new[]{.1f,.17f,.09f}){Time.deltaTime=step;Time.time+=step;foreach(var m in root.GetComponentsInChildren<WorldMotion>(true))GameObject.Call(m,"Update");foreach(var n in root.GetComponentsInChildren<HubNpcIdle>(true))GameObject.Call(n,"Update");}}
 static string Dynamic(GameObject root)=>string.Join(";",root.GetComponentsInChildren<Transform>(true).Where(t=>t.name=="Articulated working sleeve"||t.name=="Turning exchange star chart"||t.GetComponent<WorldMotion>()!=null).Select(t=>PathOf(t)+":"+Pose(t)));
 static Snapshot Execute(int group,bool enabled,string fault=null,string mode=null){Time.time=3;var root=Build(group,enabled,fault,mode);var result=Capture(root);var actual=new Dictionary<string,int>();foreach(var filter in root.GetComponentsInChildren<MeshFilter>(true)){var name=filter.transform.name;if(!keys.TryGetValue(name,out var key))continue;if(enabled&&key!=fault){Check(filter.sharedMesh.name=="Blender fixed scenery "+key,"exact mapped module for "+name);var decoded=AuthoredFixedScenery.Decode(File.ReadAllBytes(Environment.GetEnvironmentVariable("F4_ROOT")+"/Assets/Resources/FixedScenery/"+key+".bytes"),"expected");Check(MeshKey(filter.sharedMesh)==MeshKey(decoded),"loaded mesh content matches expected file "+key);UnityEngine.Object.Destroy(decoded);actual[key]=actual.TryGetValue(key,out var n)?n+1:1;}}
 if(enabled){foreach(var e in Counts(group)){int count=actual.TryGetValue(e.Key,out var n)?n:0;Check(count==(e.Key==fault?0:e.Value),"exact entire factory module multiplicity "+group+"/"+e.Key);Check(Resources.Loads.TryGetValue("FixedScenery/"+e.Key,out var loads)&&loads==1,"shared resource loaded once including cached failure "+e.Key);}}
 Check(root.GetComponentsInChildren<Collider>(true).Length==0&&root.GetComponentsInChildren<Rigidbody>(true).Length==0,"cosmetic factory has no added physics");
 Advance(root);result.Dynamic=Dynamic(root);Check(result.Nav==Nav()&&result.Marks==Marks(),"actual dynamic motion preserves navigation and occluder membership");var paused=Dynamic(root);Time.deltaTime=0;Time.time+=123;foreach(var m in root.GetComponentsInChildren<WorldMotion>(true))GameObject.Call(m,"Update");foreach(var n in root.GetComponentsInChildren<HubNpcIdle>(true))GameObject.Call(n,"Update");Check(paused==Dynamic(root),"new meshes retain actual paused motion and NPC pose");
 Dispose(root);return result;}
 static void Compare(Snapshot original,Snapshot live,Snapshot successful,string fault=null){Check(original.Nav==live.Nav,"full navigation membership matches fallback");Check(original.Marks==live.Marks,"full occlusion and building-group membership matches fallback");Check(original.Physics==live.Physics,"full collider and rigidbody membership matches fallback");Check(original.Dynamic==live.Dynamic,"actual animated joints match fallback with authored geometry");foreach(var pair in successful.Parts){var want=pair.Value;bool failed=want.Key==fault;if(failed&&want.Name.EndsWith(" fixed crest")){Check(!live.Parts.ContainsKey(pair.Key),"failed optional crest is absent");continue;}Check(live.Parts.TryGetValue(pair.Key,out var got),"complete assembly retains all expected named parts");var prior=original.Parts.TryGetValue(pair.Key,out var old)?old:null;var comparison=failed?prior:want;Check(got.Mesh==comparison.Mesh,"per-module missing/corrupt fallback equals actual original geometry");Check(got.Materials==comparison.Materials&&got.Parent==comparison.Parent,"actual palette and attachment parent unchanged");if(got.Name!="Gate frame")Check(got.Pose==comparison.Pose,"existing local transforms unchanged");if(prior!=null&&got.Key==null)Check(got.Mesh==prior.Mesh&&got.Materials==prior.Materials&&got.Pose==prior.Pose,"unmapped NPC tools and retained assembly are unchanged");}Check(live.Parts.Count==successful.Parts.Count-successful.Parts.Values.Count(x=>x.Key==fault&&x.Name.EndsWith(" fixed crest")),"no missing or extra whole-assembly renderers");}
 static void Aim(Renderer r){var b=r.bounds;var center=(b.min+b.max)*.5f;for(int i=0;i<10;i++)CameraOcclusionSurface.Advance(center+new Vector3(0,0,-8),center+new Vector3(0,0,8),.1f);}
 static void Occlusion(){var root=Build(0,true);var renderers=root.GetComponentsInChildren<Renderer>(true);var column=renderers.Single(x=>x.transform.name=="Column");var capital=renderers.Single(x=>x.transform.name=="Column band");var originalA=column.sharedMaterial;var originalB=capital.sharedMaterial;
 // Existing factory palette materials; slots are an explicit multi-material binding boundary.
 // Real authored mesh is kept. F4 currently has one submesh, so this is API lifecycle,
 // not a claim the shipped column draws three independently indexed surfaces.
 originalA.color=new Color(.2f,.4f,.6f,.8f);originalB.color=new Color(.6f,.3f,.1f,.65f);column.sharedMaterials=new[]{originalA,originalB,originalA};
 var saved=column.sharedMaterials;var colors=saved.Select(x=>x.color).ToArray();Aim(column);var faded=column.sharedMaterials;
 Check(faded.Length==3&&Enumerable.Range(0,3).All(i=>!ReferenceEquals(faded[i],saved[i])&&faded[i].name=="Camera fade (owned)"),"all material slots get owned fade clones");Check(ReferenceEquals(faded[0],faded[2])&&!ReferenceEquals(faded[0],faded[1]),"duplicate palette slots deduplicate clones");
 for(int i=0;i<3;i++){Check(Math.Abs(faded[i].color.a-colors[i].a*.2f)<.001f,"all slot alphas use actual opacity envelope");Check(saved[i].color.a==colors[i].a,"source palette alpha never mutates");Check(faded[i].renderQueue==3000&&faded[i].GetFloat("_ZWrite")==0&&faded[i].keywords.Contains("_ALPHABLEND_ON"),"owned clones receive actual fade render state");}
 CameraOcclusionSurface.RestoreAll();Check(column.sharedMaterials.SequenceEqual(saved),"all original material references restored");UnityEngine.Object.Flush();Check(faded.All(x=>x.destroyed),"owned fade copies are destroyed after restore");
 Aim(column);var replaced=column.sharedMaterials;column.sharedMaterials=new[]{replaced[0],originalA,replaced[2]};CameraOcclusionSurface.Advance(new Vector3(200,200,200),new Vector3(201,200,200),0);Check(column.sharedMaterials.SequenceEqual(new[]{originalA,originalA,originalA}),"external slot replacement preserved while remaining owned slots restore");
 column.sharedMaterials=saved;Aim(column);root.SetActive(false);Check(column.sharedMaterials.SequenceEqual(saved)&&Registry.Count==0&&Faded==0,"disable restores all slot references and registry");root.SetActive(true);Aim(column);Check(!ReferenceEquals(column.sharedMaterial,originalA),"reenabled authored surface fades again");Dispose(root);
 // Whole real workshop building: each part, multiple distinct palette materials, footprint.
 root=Build(2,true);var group=root.GetComponentsInChildren<BuildingOcclusionGroup>(true).First();var surfaces=Registry.Where(s=>ReferenceEquals(Field(s,"group"),group)).ToArray();var palette=surfaces.ToDictionary(s=>s.GetComponent<Renderer>(),s=>s.GetComponent<Renderer>().sharedMaterials);Check(palette.Values.SelectMany(x=>x).Distinct().Count()>1,"actual workshop group uses multiple existing palette materials");var roof=surfaces.First(s=>s.transform.name=="Pitched workshop roof module").GetComponent<Renderer>();Aim(roof);Check(palette.All(p=>!p.Key.sharedMaterials.SequenceEqual(p.Value)),"all actual upper building parts fade as a whole");Check(group.GetComponentsInChildren<LineRenderer>(true).Single(x=>x.transform.name=="Solid building footprint while faded").enabled,"actual building footprint enabled during group fade");CameraOcclusionSurface.RestoreAll();Check(palette.All(p=>p.Key.sharedMaterials.SequenceEqual(p.Value)),"all original material references restored");Check(!group.GetComponentsInChildren<LineRenderer>(true).Single(x=>x.transform.name=="Solid building footprint while faded").enabled,"actual building footprint hides after restore");Dispose(root);
 }
 static void Main(){var old=new Snapshot[6];var live=new Snapshot[6];for(int i=0;i<6;i++){old[i]=Execute(i,false);live[i]=Execute(i,true);Compare(old[i],live[i],live[i]);}
 var all=keys.Values.Distinct().OrderBy(x=>x).ToArray();Check(all.Length==27,"finite expected module library");foreach(var key in all)foreach(var mode in new[]{"missing","corrupt"})for(int group=0;group<6;group++)if(Counts(group).ContainsKey(key)){var fallback=Execute(group,true,key,mode);Compare(old[group],fallback,live[group],key);}
 Occlusion();Console.WriteLine("PASS "+checks+" enabled actual assembly/module/fallback/dynamic-nav/physics/occlusion assertions across "+factoryRuns+" actual six-group factory runs; 27 resources x missing/corrupt, all occurrences; actual NPC/WorldMotion/CameraOcclusionSurface. Managed, not Unity.");}
}
