using System;using System.IO;using Emberfall;using UnityEngine;
public static class MechanicKnowledgeTests{
 static int n;static void Check(bool v,string m){n++;if(!v)throw new Exception(m);}static string State(ProgressionService p)=>JsonUtility.ToJson(p.Profile,true);
 public static string Run(string root){
 var p=new ProgressionService(Path.Combine(root,"knowledge"));Check(p.CreateNewSlot(HeroClass.Ranger),"create character");p.Profile.level=30;p.Profile.mechanicMaterials=8;
 var first=p.CreateMechanicItem(EquipmentMechanic.VenomSpread);Check(p.CollectLoot(first),"own first");var source=p.Profile;string before=State(p);Directory.CreateDirectory(p.SaveFilePath+".tmp");Check(!p.ToggleMechanicVariant(first.id,true)&&p.Profile==source&&State(p)==before,"failed learning preserves materials profile and knowledge");Directory.Delete(p.SaveFilePath+".tmp");
 Check(p.ToggleMechanicVariant(first.id,true)&&p.Profile.mechanicMaterials==4&&p.Profile.variantKnowledge.Contains(EquipmentMechanic.VenomSpread),"four shards buys character mechanism knowledge");
 var second=p.CreateMechanicItem(EquipmentMechanic.VenomSpread);second.level=12;second.rarity=Rarity.Common;Check(p.CollectLoot(second),"own new copy");var current=p.Profile.inventory.Find(i=>i.id==second.id);Check(p.HasVariant(current)&&current.mechanicVariant==0,"new same mechanism knows B but keeps A");p.Profile.mechanicMaterials=0;p.Save();
 Check(!p.ToggleMechanicVariant(second.id,false),"selection camp only");Check(p.ToggleMechanicVariant(second.id,true)&&p.Profile.mechanicMaterials==0,"new copy selects learned B free");Check(p.Profile.inventory.Find(i=>i.id==second.id).level==12&&p.Profile.inventory.Find(i=>i.id==second.id).rarity==Rarity.Common,"knowledge does not inherit item growth");
 Check(p.Equip(second.id)&&p.SaveBuildPreset(0,true)&&p.ToggleMechanicVariant(second.id,true)&&p.SaveBuildPreset(1,true),"capture independent A B presets");Check(p.ApplyBuildPreset(0,true)&&p.Profile.inventory.Find(i=>i.id==second.id).mechanicVariant==1&&p.ApplyBuildPreset(1,true)&&p.Profile.inventory.Find(i=>i.id==second.id).mechanicVariant==0,"presets retain independent selected variants");
 string ranger=p.CurrentSlotId;Check(p.CreateNewSlot(HeroClass.Ranger)&&p.Profile.variantKnowledge.Count==0,"knowledge not shared across characters");Check(p.LoadSlot(ranger)&&p.Profile.variantKnowledge.Contains(EquipmentMechanic.VenomSpread),"knowledge survives reload");
 var arc=new ProgressionService(Path.Combine(root,"legacy"));Check(arc.CreateNewSlot(HeroClass.Arcanist),"create migration fixture");arc.Profile.level=30;arc.Profile.mechanicMaterials=11;var frost=arc.CreateMechanicItem(EquipmentMechanic.FrostEcho);frost.mechanicVariantUnlocked=true;frost.mechanicVariant=1;var fire=arc.CreateMechanicItem(EquipmentMechanic.CinderTrail);fire.mechanicVariantUnlocked=true;fire.mechanicVariant=0;arc.Profile.pendingLoot.Add(frost);arc.Profile.recoveryLoot.Add(fire);arc.Profile.variantKnowledgeRevision=0;arc.Profile.variantKnowledge.Clear();arc.Save();
 // Rewrite the envelope as a genuine legacy document, not a migrated Save result.
 var document=System.Text.Json.Nodes.JsonNode.Parse(File.ReadAllText(arc.SaveFilePath));document["profile"].AsObject().Remove("variantKnowledge");document["profile"].AsObject().Remove("variantKnowledgeRevision");File.WriteAllText(arc.SaveFilePath,document.ToJsonString());
 var original=arc.Profile;string disk=File.ReadAllText(arc.SaveFilePath);Directory.CreateDirectory(arc.SaveFilePath+".tmp");Check(!arc.Load()&&arc.Profile==original&&File.ReadAllText(arc.SaveFilePath)==disk,"legacy migration write failure never publishes knowledge");Directory.Delete(arc.SaveFilePath+".tmp");
 Check(arc.Load()&&arc.Profile.variantKnowledgeRevision==1&&arc.Profile.variantKnowledge.Count==2&&arc.Profile.mechanicMaterials==11,"legacy evidence unions pending recovery without refund");
 Check(arc.Load()&&arc.Profile.variantKnowledge.Count==2&&arc.Profile.mechanicMaterials==11,"migration idempotent");
 var alien=arc.CreateMechanicItem(EquipmentMechanic.VenomSpread);alien.mechanicVariantUnlocked=true;Check(!arc.HasVariant(alien),"foreign mechanism never authorized");
 return "PASS "+n+" actual character knowledge transactions";
 }}
