"""Actual panel-switch/preview ownership methods with managed boundaries; not rendered UI acceptance."""
from pathlib import Path
import tempfile,subprocess,os,sys
r=Path(__file__).resolve().parents[1]
def member(text,key):
 a=text.index(key);b=text.index('{',a)+1;depth=1
 while depth:depth+=(text[b]=='{')-(text[b]=='}');b+=1
 return text[a:b]
merchant=(r/'Assets/Scripts/UI/GameUI.Merchant.cs').read_text();grid=(r/'Assets/Scripts/UI/GameUI.InventoryGrid.cs').read_text();preview=(r/'Assets/Scripts/UI/GameUI.CollectionPreview.cs').read_text();base=(r/'Assets/Scripts/UI/GameUI.cs').read_text()
methods='\n'.join([member(merchant,'private void SelectMerchantMode('),member(merchant,'private bool StartMerchantAction('),member(grid,'private void SelectInventoryTab('),member(preview,'private void ReconcileCollectionPreview(')])
assert 'MerchantServiceLayout.StablePanelEvent(UITransitionBlocked,true,Event.current.type==EventType.Repaint||Event.current.type==EventType.Layout)' in base
expression=base[base.index('StablePanelEvent(UITransitionBlocked,')+len('StablePanelEvent(UITransitionBlocked,'):].split(',Event.current.type',1)[0]
methods+='\nprivate bool StableReplay(bool blocked,bool paint){return MerchantServiceLayout.StablePanelEvent(blocked,'+expression+',paint);}'
assert 'if (font == null) font = GameFont.Shared;' in base and 'if (invisibleButton == null) BuildStyles();' in base
fixture='''using System;using Emberfall;using UnityEngine;
namespace UnityEngine{public struct Vector2{public float x,y;public static Vector2 zero=>new Vector2();}public static class Time{public static float unscaledTime;}}
namespace Emberfall{public class Session{public bool BackgroundPaused,Paused,HasStarted=true,IsDead,ModeFinished,DungeonSelectionOpen;public Choice RunChoices=new Choice();public object Player=new object();}public class Choice{public bool AwaitingChoice;}
public class GameUI{int merchantMode,merchantSelection=-1,mobileInventoryTab;string inventoryPopupItem;float merchantActionUntil=-1;Vector2 merchantGridScroll;bool mobileInventoryDetail,inventoryComparisonOpen;enum Panel{None,Inventory,Skills,Fashion,Chests}Panel panel=Panel.Inventory;Session session=new Session();object collectionOwner;object wearModel=new object();int blocks,cancels,releases;void BlockUITransition(){blocks++;}void CancelMobileScroll(){cancels++;}void ReleaseCollectionModel(){releases++;wearModel=null;}void ReleaseCollectionPreview(){ReleaseCollectionModel();collectionOwner=null;}
METHODS
static int checks;static void C(bool b,string message){checks++;if(!b)throw new Exception(message);}public static void Main(){var u=new GameUI();u.collectionOwner=u.session.Player;object identity=u.wearModel;
for(int n=0;n<100;n++){int tab=n%3==0?0:n%3==1?2:3;u.SelectInventoryTab(tab);int blocks=u.blocks,cancels=u.cancels;u.SelectInventoryTab(tab);C(u.blocks==blocks&&u.cancels==cancels,"same inventory tab does not rebuild or reset state");u.ReconcileCollectionPreview();C(ReferenceEquals(identity,u.wearModel)&&u.releases==0,"rapid tab switching preserves actual preview ownership");}
u.session.Paused=true;for(int n=0;n<20;n++)u.ReconcileCollectionPreview();C(u.releases==0&&ReferenceEquals(identity,u.wearModel),"paused open inventory keeps cached preview instead of destroying each frame");u.session.BackgroundPaused=true;u.ReconcileCollectionPreview();C(u.wearModel==null,"hidden application releases preview resources");u.session.BackgroundPaused=false;u.session.Paused=false;u.wearModel=new object();u.panel=Panel.None;u.ReconcileCollectionPreview();C(u.wearModel==null&&u.collectionOwner==null,"closed inventory cannot retain stale owner");u.panel=Panel.Inventory;u.wearModel=new object();u.ReconcileCollectionPreview();C(ReferenceEquals(u.collectionOwner,u.session.Player),"reopen binds current owner safely");
C(u.blocks==0,"inventory same-page switching never arms global input latch");u.SelectMerchantMode(2);u.merchantSelection=1;u.SelectMerchantMode(1);C(u.merchantSelection==0,"exchange tab drops sale selection");u.SelectMerchantMode(2);C(u.merchantSelection==-1,"sale has no selection step");int count=u.blocks;u.SelectMerchantMode(2);C(u.blocks==count,"same merchant tab keeps state without rebuilding");u.SelectMerchantMode(0,true);C(u.merchantSelection==0,"merchant reopen resets purchase state");C(u.blocks==0,"merchant same-page tabs never arm global input latch");Time.unscaledTime=1;C(u.StartMerchantAction()&&!u.StartMerchantAction(),"same-frame duplicate transaction is suppressed");Time.unscaledTime=1.1f;C(!u.StartMerchantAction(),"held rapid repeated click is suppressed");Time.unscaledTime=1.4f;C(u.StartMerchantAction(),"a later deliberate action remains usable");
C(MerchantServiceLayout.StablePanelEvent(true,true,true),"transition repaint retains normal panel appearance");C(!MerchantServiceLayout.StablePanelEvent(true,true,false),"blocked interactive event still cannot mutate controls");C(!MerchantServiceLayout.StablePanelEvent(true,false,true),"other panel transitions retain prior protection");C(MerchantServiceLayout.StablePanelEvent(false,true,false),"unblocked normal input remains available");u.panel=Panel.Skills;C(u.StableReplay(true,true),"actual skills transition preserves repaint style");C(!u.StableReplay(true,false),"actual skills transition blocks input");u.panel=Panel.None;C(u.StableReplay(true,true),"all surfaces preserve appearance during transition input protection");Console.WriteLine("PASS "+checks+" actual tab state, preview ownership, repaint/input separation and duplicate-click assertions; managed boundary");}}}
'''.replace('METHODS',methods)
with tempfile.TemporaryDirectory(prefix='panel-lifecycle-') as temporary:
 p=Path(temporary);(p/'Fixture.cs').write_text(fixture)
 for name in ['MerchantServiceLayout','MobilePanelLayout']:(p/(name+'.cs')).write_text((r/('Assets/Scripts/UI/'+name+'.cs')).read_text())
 (p/'Test.csproj').write_text('<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><NuGetAudit>false</NuGetAudit><NoWarn>0649;0414</NoWarn></PropertyGroup></Project>');(p/'NuGet.Config').write_text('<configuration><packageSources><clear/></packageSources></configuration>')
 subprocess.run([sys.argv[1] if len(sys.argv)>1 else 'dotnet','run','--project',str(p/'Test.csproj')],env=dict(os.environ,DOTNET_CLI_HOME=str(p/'cli'),DOTNET_NOLOGO='1'),check=True)
