using System;using System.IO;using System.Linq;using Emberfall;using UnityEngine;
public static class PresetReplacementTests{
 static int n;static void Check(bool v,string m){n++;if(!v)throw new Exception(m);}static string State(object o)=>JsonUtility.ToJson(o,true);
 public static string Run(string root){var p=new ProgressionService(Path.Combine(root,"replace"));Check(p.CreateNewSlot(HeroClass.Ranger),"create");p.Profile.level=30;p.Profile.gold=100000;p.Profile.mechanicMaterials=8;p.Save();var bow=p.Equipped(ItemSlot.Weapon);var poison=p.CreateMechanicItem(EquipmentMechanic.VenomSpread);Check(p.CollectLoot(poison)&&p.ToggleMechanicVariant(poison.id,true)&&p.Equip(poison.id)&&p.SaveBuildPreset(0,true)&&p.SaveBuildPreset(1,true),"capture two B plans");
 var replacement=p.CreateMechanicItem(EquipmentMechanic.VenomSpread);replacement.level=20;Check(p.CollectLoot(replacement),"new candidate");
 Check(p.PresetReferences(poison.id)=="方案 A / 方案 B","both scheme references visible");
 string before=State(p.Profile),disk=File.ReadAllText(p.SaveFilePath);var q=p.QuotePresetReplacement(0,ItemSlot.Relic,replacement.id);Check(q!=null&&q.Error==null&&State(p.Profile)==before,"quote does not apply anything");
 Check(q.Summary.Contains("选择 B")&&q.Summary.Contains("继承部位强化"),"quote states variant and trained stats");Check(!p.ReplacePresetEquipment(q,false)&&State(p.Profile)==before,"outside camp refused");Directory.CreateDirectory(p.SaveFilePath+".tmp");Check(!p.ReplacePresetEquipment(q,true)&&State(p.Profile)==before&&File.ReadAllText(p.SaveFilePath)==disk,"failed single reference transaction atomic");Directory.Delete(p.SaveFilePath+".tmp");
 string other=State(p.Profile.buildPresets[1]);string skills=State(p.Profile.skillRanks);string mastery=State(p.Profile.masteryRanks);string keys=State(p.Profile.hotbarKeys);var plan=p.Profile.buildPresets[0];string planSkills=State(plan.skillRanks);string armor=plan.armorId,weapon=plan.weaponId;int core=plan.masteryCore;
 Check(p.ReplacePresetEquipment(q,true),"confirmed explicit replacement");plan=p.Profile.buildPresets[0];Check(plan.relicId==replacement.id&&plan.equipmentVariants[2]==1&&plan.armorId==armor&&plan.weaponId==weapon&&plan.masteryCore==core&&State(plan.skillRanks)==planSkills,"only selected plan slot changes");Check(State(p.Profile.buildPresets[1])==other&&p.Profile.relicId==poison.id&&State(p.Profile.skillRanks)==skills&&State(p.Profile.masteryRanks)==mastery&&State(p.Profile.hotbarKeys)==keys,"repair never applies current build or overwrites other plan");Check(!p.ReplacePresetEquipment(q,true),"duplicate quote cannot apply");
 var ui=new GameUI();ui.Attach(p);ui.Select(0,ItemSlot.Relic,poison.id);before=State(p.Profile);ui.Cancel();ui.Confirm();Check(State(p.Profile)==before,"actual UI cancellation never writes");ui.Select(0,ItemSlot.Relic,poison.id);var same=p.Profile;Check(p.Upgrade(p.Profile.weaponId)&&p.Profile==same,"actual upgrade mutates same profile");before=State(p.Profile);ui.Confirm();Check(State(p.Profile)==before&&p.Profile.buildPresets[0].relicId==replacement.id,"actual UI rejects in-place upgrade stale quote");ui.Select(0,ItemSlot.Relic,poison.id);ui.Confirm();Check(p.Profile.buildPresets[0].relicId==poison.id,"actual UI request preview confirm replaces target only");
 q=p.QuotePresetReplacement(0,ItemSlot.Relic,"missing");Check(q.Error!=null&&!p.ReplacePresetEquipment(q,true),"missing candidate refused");var high=p.CreateMechanicItem(EquipmentMechanic.VenomSpread);high.level=40;Check(p.CollectLoot(high)&&p.QuotePresetReplacement(0,ItemSlot.Relic,high.id).Error!=null,"over-level candidate refused");
 var ordinary=new ItemData{id=Guid.NewGuid().ToString("N"),name="plain relic",slot=ItemSlot.Relic,rarity=Rarity.Common,level=1};Check(p.CollectLoot(ordinary),"ordinary candidate owned");Check(p.QuotePresetReplacement(0,ItemSlot.Relic,ordinary.id).Error!=null,"required B never silently lost");Check(p.ReplacePresetEquipment(p.QuotePresetReplacement(0,ItemSlot.Relic,ordinary.id,0),true)&&p.Profile.buildPresets[0].equipmentVariants[2]==-1,"explicit A choice may drop mechanism with disclosed preview");
 Check(p.PresetReplacementCandidates(1,ItemSlot.Relic)[0].mechanic==EquipmentMechanic.VenomSpread,"same mechanism sorted first");Check(p.PresetReferences(ordinary.id)=="方案 A"&&!p.Sell(ordinary.id)&&p.PresetReferences(poison.id)=="方案 B","reference markers and sale require confirmation");ui.AskSale(ordinary.id);ui.CancelSale();ui.ConfirmSale();Check(p.Profile.inventory.Exists(i=>i.id==ordinary.id),"actual sale cancel retains referenced item");ui.AskSale(ordinary.id);Check(p.Upgrade(p.Profile.weaponId),"upgrade while sale confirmation open");ui.ConfirmSale();Check(p.Profile.inventory.Exists(i=>i.id==ordinary.id),"actual sale rejects stale in-place change");ui.AskSale(ordinary.id);ui.ConfirmSale();Check(!p.Profile.inventory.Exists(i=>i.id==ordinary.id)&&!string.IsNullOrEmpty(p.BuildPresetLockReason(0,true)),"actual confirmed sale leaves explicit missing reference");Check(p.ReplacePresetEquipment(p.QuotePresetReplacement(0,ItemSlot.Relic,replacement.id,1),true),"manual repair missing reference with learned B");
 var spare=new ItemData{id=Guid.NewGuid().ToString("N"),name="spare armor",slot=ItemSlot.Armor,rarity=Rarity.Common,level=1};Check(p.CollectLoot(spare)&&p.ReplacePresetEquipment(p.QuotePresetReplacement(0,ItemSlot.Armor,spare.id),true),"plan references spare low-quality");Check(p.BulkSalePresetImpact().Contains("方案 A")&&p.BulkSellLowQuality()==0&&p.Profile.inventory.Exists(i=>i.id==spare.id),"bulk cleanup blocks before referenced loss");Check(p.BulkSellLowQuality(true)>0&&!p.Profile.inventory.Exists(i=>i.id==spare.id),"bulk explicit confirmation works");
 Check(p.Load()&&p.Profile.buildPresets[0].relicId==replacement.id&&p.Profile.buildPresets[0].equipmentVariants[2]==1,"selected replacement persists without losing B");
 p.Profile.buildPresets[0].equipmentMechanics=null;p.Profile.buildPresets[0].equipmentVariants=null;p.Save();Check(p.Load()&&p.Profile.buildPresets[0].equipmentMechanics==null&&!string.IsNullOrEmpty(p.BuildPresetLockReason(0,true)),"legacy missing references never auto-replaced on load");var legacy=p.QuotePresetReplacement(0,ItemSlot.Armor,p.Profile.armorId);Check(legacy.Summary.Contains("未知（旧方案未记录）")&&p.ReplacePresetEquipment(legacy,true),"legacy missing metadata disclosed then explicit repair");
 var otherRole=new ProgressionService(Path.Combine(root,"unlearned"));Check(otherRole.CreateNewSlot(HeroClass.Ranger),"create unlearned character");var unlearned=otherRole.CreateMechanicItem(EquipmentMechanic.VenomSpread);Check(otherRole.CollectLoot(unlearned)&&otherRole.SaveBuildPreset(0,true)&&otherRole.QuotePresetReplacement(0,ItemSlot.Relic,unlearned.id,1).Error!=null,"unlearned real mechanism cannot claim B through repair");

 var oldRole=new ProgressionService(Path.Combine(root,"two-missing"));Check(oldRole.CreateNewSlot(HeroClass.Arcanist),"create two missing legacy fixture");oldRole.Profile.level=30;oldRole.Save();Check(oldRole.SaveBuildPreset(0,true)&&oldRole.SaveBuildPreset(1,true),"record fixture before old metadata removal");
 var oldPlan=oldRole.Profile.buildPresets[0];oldPlan.weaponId="legacy-lost-weapon";oldPlan.relicId="legacy-lost-relic";oldPlan.equipmentMechanics=null;oldPlan.equipmentMechanicKnownMask=0;
 var newRelic=oldRole.CreateMechanicItem(EquipmentMechanic.FrostEcho);var newWeapon=oldRole.CreateMechanicItem(EquipmentMechanic.CinderTrail);Check(oldRole.CollectLoot(newRelic)&&oldRole.CollectLoot(newWeapon),"own explicit legacy repair candidates");oldRole.Save();Check(oldRole.Load(),"read actual legacy two missing preset");
 string untouchedPlan=State(oldRole.Profile.buildPresets[1]),untouchedSkills=State(oldRole.Profile.buildPresets[0].skillRanks),untouchedMastery=State(oldRole.Profile.buildPresets[0].masteryRanks),untouchedKeys=State(oldRole.Profile.buildPresets[0].hotbarKeys);string untouchedArmor=oldRole.Profile.buildPresets[0].armorId;int untouchedCore=oldRole.Profile.buildPresets[0].masteryCore;
 var legacyUI=new GameUI();legacyUI.Attach(oldRole);legacyUI.Select(0,ItemSlot.Relic,newRelic.id);legacyUI.Confirm();legacyUI.Select(0,ItemSlot.Weapon,newWeapon.id);
 Check(legacyUI.Preview.Contains("未知（旧方案未记录）")&&oldRole.QuotePresetReplacement(0,ItemSlot.Weapon,newWeapon.id).Summary.Contains("未知（旧方案未记录）"),"partial legacy repair keeps missing weapon unknown in actual UI");
 Check(oldRole.PresetReplacementCandidates(0,ItemSlot.Weapon)[0].id==newWeapon.id,"unknown mechanism does not prefer ordinary None over higher legal candidate");
 oldPlan=oldRole.Profile.buildPresets[0];Check(oldPlan.weaponId=="legacy-lost-weapon"&&oldPlan.relicId==newRelic.id&&oldPlan.armorId==untouchedArmor&&oldPlan.masteryCore==untouchedCore&&State(oldPlan.skillRanks)==untouchedSkills&&State(oldPlan.masteryRanks)==untouchedMastery&&State(oldPlan.hotbarKeys)==untouchedKeys&&State(oldRole.Profile.buildPresets[1])==untouchedPlan,"partial legacy repair preserves other refs allocations selections and other preset");
 Check((oldPlan.equipmentMechanicKnownMask&1)==0&&(oldPlan.equipmentMechanicKnownMask&6)==6,"only owned armor and selected relic have known metadata");Check(oldRole.Load()&&oldRole.QuotePresetReplacement(0,ItemSlot.Weapon,newWeapon.id).Summary.Contains("未知（旧方案未记录）"),"per-slot unknown survives durable reload");
 return "PASS "+n+" actual preset replacement and UI transaction assertions";
}}
namespace UnityEngine{public struct Vector2{public static Vector2 zero=>new Vector2();}}
namespace Emberfall{
 public class PlayerController{}public class TestPlanSession{public ProgressionService Progression;public PlayerController Player=new PlayerController();public bool IsInCamp=true,IsDead,PracticeActive;public void Notify(string s){}}
 public partial class GameUI{
 enum BuildPlanAction{None,Reset,Save,Apply,Replace}enum Panel{Camp,Inventory}Panel panel=Panel.Camp;object allocationDraft=null;
 bool buildPlansOpen,buildPlanChoosing;ItemSlot buildPlanPart;ProgressionService.PresetEquipmentQuote buildPlanReplacement;string buildPlanFingerprint;BuildPlanAction buildPlanAction;int buildPlanSlot;ProgressionService buildPlanOwner;PlayerController buildPlanHero;string buildPlanCharacterId;GameProfile buildPlanSource;string buildPlanPreview,buildPlanError;Vector2 buildPlanScroll;TestPlanSession session;
 Vector2 presetSaleScroll;bool presetSaleOpen,presetSaleBulk;string presetSaleId,presetSaleState,presetSaleImpact,presetSaleError;ProgressionService presetSaleOwner;void Feedback(bool success,string message){}void SellInventoryItem(string id,bool confirmed){throw new Exception("unexpected unreferenced sale");}void RebuildBagItems(){}void ResolveSelectedItem(){}
 public void AskSale(string id){RequestPresetSale(id);}public void ConfirmSale(){ConfirmPresetSale();}public void CancelSale(){CancelPresetSale();}
 void CancelMobileScroll(){}void BlockUITransition(){}void CancelAllocationDraft(){throw new Exception("unexpected draft");}
 public string Preview=>buildPlanPreview;public void Attach(ProgressionService p){session=new TestPlanSession{Progression=p};}public void Select(int plan,ItemSlot slot,string id){BeginPresetReplacement(plan,slot);PreviewPresetReplacement(id);}public void Confirm(){ConfirmBuildPlanAction();}public void Cancel(){CloseBuildPlanSurface();}
 }}
