using System;using Emberfall;using UnityEngine;
public static class RoomBranchProductionTests{
 static int n;static void C(bool b,string m){n++;if(!b)throw new Exception(m);}
 static void Complete(GameSession s){var p=s.RoomChainRun.Room;foreach(var e in s.Enemies)s.Kill(e);if(!p.Boss&&!p.Interlude){if(p.Objective==RoomObjective.Purify){for(int seal=0;seal<2;seal++){s.Player.Teleport(s.Markers[seal].transform.position);for(int i=0;i<12;i++)s.Tick();}}else if(p.Objective==RoomObjective.Escape){s.Player.Teleport(new Vector3(0,0,11));for(int i=0;i<16;i++)s.Tick();}}}
 static void Door(GameSession s){s.Player.Teleport(new Vector3(0,0,14));}
 public static void Main(){
 for(int seed=0;seed<54;seed++)foreach(RoomBranch branch in new[]{RoomBranch.Seal,RoomBranch.Supply}){
 var s=new GameSession(seed);int originalTier=s.DungeonTier;bool originalLimited=s.ChallengeRun;var run=s.RoomChainRun;C(!s.ConfirmRoomBranch(branch),"early branch rejected");Complete(s);s.Tick();s.Tick();C(s.ConfirmBlessingForTest(0),"first blessing remains");Door(s);C(s.EnterNextRoom()&&run.Room.Index==1,"first transition real host");Complete(s);Door(s);var old=run.Room;int epoch=s.Player.CombatEpoch,count=s.Enemies.Count;
 C(!s.EnterNextRoom()&&s.RoomBranchChoiceOpen&&s.InputBlocked&&Time.timeScale==0,"second door opens blocked selection without generation");C(ReferenceEquals(old,run.Room)&&count==s.Enemies.Count&&epoch==s.Player.CombatEpoch,"unselected branch never generated");
 s.CancelRoomBranchChoice();C(!s.RoomBranchChoiceOpen&&ReferenceEquals(old,run.Room)&&run.SelectedBranch==RoomBranch.None,"back preserves second room and no selection");C(!s.EnterNextRoom()&&s.RoomBranchChoiceOpen,"reopen choice");s.Paused=true;C(!s.ConfirmRoomBranch(branch),"pause blocks selection");s.Paused=false;s.Background(true);C(!s.ConfirmRoomBranch(branch)&&s.RoomBranchChoiceOpen,"background preserves undecided choice");s.Background(false);s.Progression.Fail=true;C(!s.ConfirmRoomBranch(branch)&&run.SelectedBranch==RoomBranch.None&&s.RoomBranchChoiceOpen,"failed save retains undecided live room");s.Progression.Fail=false;
 C(s.ConfirmRoomBranch(branch),"confirm transitions actual host");C(run.Room.Index==2&&run.Room.Branch==branch&&run.Room.Objective==(branch==RoomBranch.Seal?RoomObjective.Purify:RoomObjective.Hunt),"selected objective replaces old seed objective");C(!run.Failed&&s.Enemies.Count==(branch==RoomBranch.Seal?4:6),"only selected finite roster spawned reachable");C(!s.ConfirmRoomBranch(branch)&&!s.EnterNextRoom(),"duplicate click cannot advance");C(!run.Defeat(old,0),"old callback rejected");C(s.RoomSupplyActive==(branch==RoomBranch.Supply),"supply only in chosen supply branch");
 var positions=new Vector3[s.Enemies.Count];for(int i=0;i<positions.Length;i++)positions[i]=s.Enemies[i].transform.position;
 s.Fail();C(!s.RoomBranchChoiceOpen&&s.CanRetryRoomChain,"failed run exposes retry");int before=s.Player.CombatEpoch;int rngCalls=UnityEngine.Random.Calls,history=s.History;string receipt=s.Receipt;s.Progression.Fail=true;C(!s.RetryFailedRoomChain()&&ReferenceEquals(run,s.RoomChainRun),"failed retry save retains old state");s.Progression.Fail=false;s.SelectedDungeonTier=7;s.SelectedArenaMode=0;C(s.RetryFailedRoomChain(),"actual retry admission and reset");C(s.RoomChainRun.Room.Seed==seed&&s.RoomChainRun.SelectedBranch==branch&&s.RoomChainRun.Room.Index==0&&s.DungeonTier==originalTier&&s.ChallengeRun==originalLimited,"retry retains seed branch and conditions");C(UnityEngine.Random.Calls==rngCalls&&s.History==history&&receipt!=s.Receipt&&!string.IsNullOrEmpty(s.Receipt),"retry skips RNG and seed history rotation and creates new receipt");C(!ReferenceEquals(run,s.RoomChainRun)&&s.Player.CombatEpoch==before+1&&!s.IsDead&&!s.RetryFailedRoomChain(),"retry creates fresh state epoch and blocks duplicate");
 Complete(s);s.Tick();s.Tick();C(s.ConfirmBlessingForTest(0),"retry first blessing");Door(s);C(s.EnterNextRoom(),"retry second");Complete(s);Door(s);C(s.EnterNextRoom()&&!s.RoomBranchChoiceOpen,"retry selected branch enters directly");for(int i=0;i<positions.Length;i++)C((s.Enemies[i].transform.position-positions[i]).sqrMagnitude<.00001f,"same seed path positions");
 Complete(s);Door(s);C(s.EnterNextRoom()&&!s.RoomChainRun.Room.Interlude&&s.RoomChainRun.Room.EnemyCount>0,"fourth combat encounter");Complete(s);Door(s);C(s.EnterNextRoom()&&s.RoomChainRun.Room.Boss,"fifth boss convergence");Complete(s);C(s.RoomChainRun.Finished&&!s.RoomChainRun.Failed&&s.RunChoices.ActiveCountForTest()==1,"five combat rooms retain opening blessing");int ordinaryWrites=s.Progression.Saves;s.Fresh();C(s.Progression.Saves==ordinaryWrites+2,"ordinary camp exit and new entry each retain their own preflight");C(s.RoomChainRun!=null&&s.RoomChainRun.SelectedBranch==RoomBranch.None,"new expedition resets branch");
 }
 var exit=new GameSession(0);Complete(exit);exit.Tick();exit.Tick();exit.ConfirmBlessingForTest(0);Door(exit);exit.EnterNextRoom();Complete(exit);Door(exit);exit.EnterNextRoom();var abandoned=exit.RoomChainRun;C(exit.ExitForTest()&&exit.RoomChainRun==null&&!abandoned.BranchChoiceOpen&&!exit.CanRetryRoomChain,"exit disposes pending choice and retry context");
 var died=new GameSession(0);Complete(died);died.Tick();died.Tick();died.ConfirmBlessingForTest(0);Door(died);died.EnterNextRoom();Complete(died);Door(died);died.EnterNextRoom();died.Fail();C(!died.RoomBranchChoiceOpen&&!died.ConfirmRoomBranch(RoomBranch.Seal),"death cancels pending selection");C(died.RetryFailedRoomChain()&&died.RoomChainRun.SelectedBranch==RoomBranch.None,"retry before selection remains undecided");
 var failed=new GameSession(0);Complete(failed);failed.Tick();failed.Tick();failed.ConfirmBlessingForTest(0);Door(failed);failed.EnterNextRoom();Complete(failed);Door(failed);failed.EnterNextRoom();WorldBuilder.FailNextBuild=true;C(!failed.ConfirmRoomBranch(RoomBranch.Supply)&&failed.RoomChainRun.Failed&&!failed.Changing&&!failed.RoomBranchChoiceOpen,"world generation failure closes branch and transition gate");C(failed.RetryFailedRoomChain()&&failed.RoomChainRun.SelectedBranch==RoomBranch.Supply,"failed generation retains confirmed branch for retry");
var atomic=new GameSession(0);Complete(atomic);atomic.Tick();atomic.Tick();atomic.ConfirmBlessingForTest(0);Door(atomic);atomic.EnterNextRoom();Complete(atomic);Door(atomic);atomic.EnterNextRoom();var secondRoom=atomic.RoomChainRun.Room;int priorEpoch=atomic.Player.CombatEpoch,priorWrites=atomic.Progression.Saves;
 atomic.Progression.FailOnSave=priorWrites+1;C(!atomic.ConfirmRoomBranch(RoomBranch.Seal)&&ReferenceEquals(secondRoom,atomic.RoomChainRun.Room)&&atomic.RoomChainRun.SelectedBranch==RoomBranch.None&&atomic.RoomBranchChoiceOpen&&atomic.InputBlocked&&Time.timeScale==0&&atomic.Player.CombatEpoch==priorEpoch,"first-write fault leaves branch panel and input transaction unchanged");
 priorWrites=atomic.Progression.Saves;atomic.Progression.FailOnSave=priorWrites+2;C(atomic.ConfirmRoomBranch(RoomBranch.Supply)&&atomic.RoomChainRun.Room.Index==2&&atomic.RoomChainRun.SelectedBranch==RoomBranch.Supply,"single preflight enters selected room despite second-write fault");C(atomic.Progression.Saves==priorWrites+1&&atomic.Player.CombatEpoch==priorEpoch+1&&!atomic.RoomBranchChoiceOpen&&!atomic.InputBlocked,"one branch confirmation performs exactly one save and one epoch transition");
 var selectedRoom=atomic.RoomChainRun.Room;C(!atomic.ConfirmRoomBranch(RoomBranch.Seal)&&!atomic.ConfirmRoomBranch(RoomBranch.Supply)&&ReferenceEquals(selectedRoom,atomic.RoomChainRun.Room)&&atomic.Progression.Saves==priorWrites+1&&atomic.Player.CombatEpoch==priorEpoch+1,"repeated branch confirmation neither writes nor changes room twice");
var retry=new GameSession(3);retry.Fail();var failedState=retry.RoomChainRun;int retryEpoch=retry.Player.CombatEpoch,retryWrites=retry.Progression.Saves,retryHistory=retry.History;string retryReceipt=retry.Receipt;retry.SelectedArenaMode=0;retry.SelectedDungeonTier=7;
 retry.Progression.FailOnSave=retryWrites+1;C(!retry.RetryFailedRoomChain()&&ReferenceEquals(failedState,retry.RoomChainRun)&&retry.Player.CombatEpoch==retryEpoch&&retry.Receipt==retryReceipt&&retry.History==retryHistory&&retry.SelectedArenaMode==0&&retry.SelectedDungeonTier==7&&retry.IsDead&&retry.CanRetryRoomChain,"retry first-save failure preserves state receipt epoch selections and same-frame retry eligibility");
 retryWrites=retry.Progression.Saves;retry.Progression.FailOnSave=retryWrites+2;C(retry.RetryFailedRoomChain()&&retry.Progression.Saves==retryWrites+1,"retry uses one saved preflight despite second-write fault");C(!ReferenceEquals(failedState,retry.RoomChainRun)&&retry.Player.CombatEpoch==retryEpoch+1&&retry.Receipt!=retryReceipt&&!retry.IsDead,"single-save retry rebuilds state and receipt once");var restarted=retry.RoomChainRun;C(!retry.RetryFailedRoomChain()&&ReferenceEquals(restarted,retry.RoomChainRun)&&retry.Progression.Saves==retryWrites+1&&retry.Player.CombatEpoch==retryEpoch+1,"duplicate retry does not save or rebuild twice");
 var art=new GameSession(0);Complete(art);art.Tick();art.Tick();art.ConfirmBlessingForTest(0);Door(art);art.EnterNextRoom();Complete(art);Door(art);art.EnterNextRoom();WorldBuilder.SealCalls=0;WorldBuilder.FailSealNumber=2;
 C(!art.ConfirmRoomBranch(RoomBranch.Seal)&&art.RoomChainRun.Failed,"second seal model failure terminates without completion");C(art.RoomGenerationFailureDetail.Contains("印记模型与进度 2")&&Debug.LastError.Contains("种子 0")&&!art.RoomGenerationFailureDetail.Contains("种子")&&art.RoomGenerationFailureDetail.Contains("房间 3"),"retain exact third-room failure stage and seed");C(Debug.LastException is InvalidOperationException&&Debug.LastException.StackTrace.Contains("MakeRoomObjective"),"native logging preserves exception stack");C(art.LastNotice.StartsWith("构建异常")&&!art.LastNotice.Contains("种子")&&!art.LastNotice.Contains("房间 3 / 5"),"success notice never overwrites failure");WorldBuilder.FailSealNumber=0;
 var first=new GameSession(0);first.ExitForTest();WorldBuilder.FailNextBeacon=true;first.SelectDungeonForTest();
 C(first.RoomChainRun!=null&&first.RoomChainRun.Failed&&first.InputBlocked&&!first.SelectionOpen,"first entry construction failure retains terminal state");
 C(first.LastNotice.StartsWith("构建异常")&&!first.LastNotice.Contains("回廊远征 · "),"first entry success notice never overwrites generation failure");
 C(first.RoomGenerationFailureDetail.Contains("北门标记")&&Debug.LastError.Contains("种子")&&Debug.LastException!=null,"first entry retains readable stage and developer evidence");WorldBuilder.FailSealNumber=0;
 Console.WriteLine("PASS: "+n+" actual branch host assertions, 54 seeds x 2 paths (managed boundary doubles, not Unity)");
 }
}
namespace Emberfall{public sealed partial class GameSession{public bool ConfirmBlessingForTest(int i)=>ConfirmRoomInterlude(i);}public static class ChoiceCount{public static int ActiveCountForTest(this RunChoices r){int n=0;foreach(var b in r.Active)n++;return n;}}}
