"""Replay compact mastery production drawing and dispatch with explicit service/GUI boundaries."""
from pathlib import Path
import os,sys,tempfile,subprocess
root=Path(__file__).resolve().parents[1]
s=(root/'Assets/Scripts/UI/GameUI.SkillIntegration.cs').read_text();a=s.index('        private int selectedMastery');methods=s[s.index('        private string SkillMasterySummary()'):s.rfind('    }')]
g=(root/'Assets/Scripts/Core/GameTypes.cs').read_text();ga=g.index('public static class MasteryProgressionRules');gb=g.index('{',ga)+1;depth=1
while depth:depth+=(g[gb]=='{')-(g[gb]=='}');gb+=1
actual_rules=g[ga:gb]
fixture=r'''
using System;using System.Collections.Generic;using UnityEngine;
namespace UnityEngine{
 public struct Vector2{public float x,y;}public struct Rect{public float x,y,width,height;public Rect(float a,float b,float c,float d){x=a;y=b;width=c;height=d;}public float xMax=>x+width;public float yMax=>y+height;public Vector2 center=>new Vector2{x=x+width/2,y=y+height/2};public bool Contains(Vector2 p)=>p.x>=x&&p.x<xMax&&p.y>=y&&p.y<yMax;}
 public struct Color{public static Color white=>default;public static Color operator*(Color c,float f)=>c;}
 public class GUIContent{public string text;public GUIContent(string s){text=s;}public static GUIContent none=new GUIContent("");}public enum TextAnchor{MiddleCenter}
 public static class GUI{public static int Target=-1,Index;public static bool Button(Rect r,GUIContent c,object style)=>Index++==Target;}
 public static class Mathf{public static int RoundToInt(float n)=>(int)Math.Round(n);public static float Min(float a,float b)=>Math.Min(a,b);public static float Max(float a,float b)=>Math.Max(a,b);public static int Clamp(int n,int a,int b)=>Math.Max(a,Math.Min(b,n));}
}
namespace Emberfall{
 enum HeroClass{Vanguard,Arcanist,Ranger,Summoner}enum MasteryType{Offense,Vitality,Guard,Technique}enum ElementalistSpecialization{None,Shatter,Burn}
 class Profile{public HeroClass heroClass=HeroClass.Arcanist;public int level=80,skillPoints=20,masteryCore=-1;public int[] masteryRanks={0,1,10,20};public ElementalistSpecialization specialization=ElementalistSpecialization.Shatter;}
 class ProgressionService{public Profile Profile=new Profile();public int RefundableBuildPoints=15,RefundableSkillRanks=3,Learned=-1,Core=-1,Refunds,Resets,Specialization;public static int MasteryCap(int l)=>MasteryProgressionRules.Cap(l);public bool HasBuildPreset(int i)=>i==1;public string MasteryLockReason(MasteryType m)=>MasteryCap(Profile.level)==0?"未解锁":Profile.masteryRanks[(int)m]>=MasteryCap(Profile.level)?"满级":Profile.skillPoints==0?"缺点数":"";public bool HasMasteryCore(MasteryType m)=>Profile.masteryCore==(int)m;public int MasteryCoreTier(MasteryType m)=>Profile.masteryRanks[(int)m]>=MasteryProgressionRules.EnhancedInvestment?2:1;public bool LearnMastery(MasteryType m){if(MasteryLockReason(m)!="")return false;Learned=(int)m;Profile.masteryRanks[Learned]++;Profile.skillPoints--;return true;}public bool SelectMasteryCore(MasteryType m,bool camp){Core=(int)m;Profile.masteryCore=Core;return camp;}public bool RefundSkillRanks(bool camp){Refunds++;return camp;}public bool ResetMastery(bool camp){Resets++;return camp;}public bool SetSpecialization(ElementalistSpecialization m,bool camp){Specialization++;return camp;}}
 class Session{public bool IsInCamp=true;public ProgressionService Progression=new ProgressionService();}
 static class GameBalance{public static string ClassName(HeroClass c)=>c.ToString();}
 static class BuildCatalog{public static string ClassSignatureDescription(HeroClass c)=>"signature";public static string MasteryName(MasteryType m)=>"破敌精通";public static string MasteryDescription(MasteryType m)=>"Each point changes real attributes; the selected core has actual cooldown and threshold. "+m;}
 static class MasteryCoreRules{public const int InitialInvestment=MasteryProgressionRules.InitialInvestment,EnhancedInvestment=MasteryProgressionRules.EnhancedInvestment;}static class MobileControls{public static bool Active=true;}
 static class UIIconAtlas{public static object Utility(string s)=>s;public static object SkillGlyph(HeroClass c,int i)=>i;public static object Mastery(MasteryType m)=>m;}
 enum CampRouteAction{None,Skill}class Route{public string Name="Route",Loop="Loop",Requirements="Requirement",Enhancement="Enhancement",NextStep="Step";public bool Ready=true;public CampRouteAction NextAction=CampRouteAction.Skill;}
 static class CampRouteCards{public static Route Describe(Profile p,bool mobile,int i)=>new Route();}
 partial class GameUI{
 Session session=new Session();Color pale,jade,gold,muted;Vector2 Mouse;object invisibleButton;string tooltip;int Opens,RouteCalls,Requests,RequestSlot,ResultCalls;enum BuildPlanAction{Save,Apply,Reset}BuildPlanAction Requested;
 int SelectedMarkers;string Click;int Ordinal=1,Seen;float Scale=1;List<Rect> Targets=new List<Rect>();List<bool> Enables=new List<bool>();List<string> Captions=new List<string>();
 bool InventoryPictogramAction(Rect r,string s,object icon,bool enabled=true,bool selected=false,bool throttle=false){Targets.Add(r);Enables.Add(enabled);Captions.Add(s);if(s!=Click)return false;Seen++;return enabled&&Seen==Ordinal;}
 void OpenClassSwitch(){Opens++;}void RequestBuildPlanAction(BuildPlanAction a,int slot=0){Requested=a;RequestSlot=slot;Requests++;}void MobileWorkshopResult(bool ok,string msg){ResultCalls++;}void CancelMobileScroll(){}void BlockUITransition(){}void FollowCampRouteStep(Route r,int index){RouteCalls++;}
 void Text(Rect r,string s,int n,Color c,bool bold=false,bool wrap=false,TextAnchor align=TextAnchor.MiddleCenter){}void DrawIcon(Rect r,object icon,Color c){if(icon is string v&&v=="confirm")SelectedMarkers++;}void Border(Rect r,Color c){}void Fill(Rect r,Color c){}
 class Metrics{public int Font;public float Scale;public float CalcHeight(GUIContent c,float w)=>Math.Max(1,(float)Math.Ceiling(c.text.Length*Font*Scale/w))*Font*Scale*1.2f;}Metrics Style(int n,bool bold,bool wrap)=>new Metrics{Font=n,Scale=Scale};
 void Draw(float width=520,float u=1,string click=null,int ordinal=1,int node=-1){Click=click;Ordinal=ordinal;Seen=0;GUI.Index=0;GUI.Target=node;SelectedMarkers=0;Targets.Clear();Enables.Clear();Captions.Clear();float measured=DrawSkillDevelopmentContent(width,u,false);float actual=DrawSkillDevelopmentContent(width,u,true);C(Math.Abs(measured-actual)<.02,"measured content equals actual draw bounds");}
 static int count;static void C(bool b,string s){count++;if(!b)throw new Exception(s);}
 public static void Main(){foreach(float width in new[]{520f,700f,900f})foreach(float u in new[]{.85f,1f,1.5f})foreach(float text in new[]{1f,1.2f}){var ui=new GameUI{Scale=text};ui.Draw(width,u);C(ui.Targets.Count==16&&GUI.Index==4,"compact tool, four upgrades, core/reset and routes retain dispatch targets");foreach(var r in ui.Targets)C(r.width>=44*u&&r.height>=44*u&&r.x>=0&&r.xMax<=width*u+.01,"every action retains bounded touch target");C(ui.SelectedMarkers==1,"selected branch has a graphic marker independent of color");C(ui.Opens==0&&ui.Requests==0&&ui.session.Progression.Learned==-1,"measure/draw does not mutate ownership without input");}
 var low=new GameUI();low.session.Progression.Profile.level=1;low.session.Progression.Profile.masteryRanks=new int[4];low.Draw(click:"未解锁");C(low.Captions.FindAll(s=>s=="未解锁").Count==4&&!low.Captions.Contains("已满")&&low.session.Progression.Learned==-1,"actual pre-unlock tier shows locked nodes, never false completed caps");C(MasteryProgressionRules.FirstUnlockLevel==30&&ProgressionService.MasteryCap(29)==0&&ProgressionService.MasteryCap(30)==5,"UI derives unlock boundary from production rules");
 var v=new GameUI();v.Draw(click:"记录",ordinal:1);C(v.Requested==BuildPlanAction.Save&&v.RequestSlot==0,"A save enters existing confirmation");v.Draw(click:"记录",ordinal:2);C(v.Requested==BuildPlanAction.Save&&v.RequestSlot==1,"B save enters existing confirmation");int req=v.Requests;v.Draw(click:"应用",ordinal:1);C(v.Requests==req,"empty A cannot apply");v.Draw(click:"应用",ordinal:2);C(v.Requested==BuildPlanAction.Apply&&v.RequestSlot==1,"owned B enters existing apply confirmation");v.Draw(click:"返还 15");C(v.Requested==BuildPlanAction.Reset,"combined reset preserves confirmation");
 v.Draw(node:2);C(v.selectedMastery==2,"node selection remains same page");v.Draw(click:"1 点",ordinal:3);C(v.session.Progression.Learned==2,"upgrade acts on clicked branch, not stale selected node");v.Draw(click:"启用核心");C(v.session.Progression.Core==2,"selected core switches through existing camp service");
 v.session.Progression.Profile.skillPoints=0;int learned=v.session.Progression.Learned;v.Draw(click:"缺点数");C(v.session.Progression.Learned==learned,"no points cannot invoke learn");v.session.Progression.Profile.masteryRanks[0]=20;v.Draw(click:"已满");C(v.session.Progression.Learned==learned,"capped node cannot overspend");
 v.session.IsInCamp=false;req=v.Requests;int core=v.session.Progression.Core;v.Draw(click:"返还 15");v.Draw(click:"记录");v.Draw(click:"退进阶");v.Draw(click:"退精通");v.Draw(click:"均衡");C(v.Requests==req&&v.session.Progression.Refunds==0&&v.session.Progression.Resets==0&&v.session.Progression.Specialization==0&&v.session.Progression.Core==core,"outside camp gates plans, reset, specialization and cores");
 Console.WriteLine("PASS "+count+" compact mastery production measure, dispatch, confirmation, selection, points and camp-gate assertions; managed boundary");}
 METHODS
 }
}
'''.replace('METHODS',methods).replace('enum HeroClass{',actual_rules+'\nenum HeroClass{')
with tempfile.TemporaryDirectory(prefix='skill-development-') as t:
 p=Path(t);(p/'Fixture.cs').write_text(fixture);(p/'Layout.cs').write_text((root/'Assets/Scripts/UI/MobilePanelLayout.cs').read_text());(p/'Test.csproj').write_text('<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><NuGetAudit>false</NuGetAudit><NoWarn>0649;0414</NoWarn></PropertyGroup></Project>');(p/'NuGet.Config').write_text('<configuration><packageSources><clear/></packageSources></configuration>');subprocess.run([sys.argv[1] if len(sys.argv)>1 else 'dotnet','run','--project',str(p/'Test.csproj')],env=dict(os.environ,DOTNET_CLI_HOME=str(p/'cli'),DOTNET_NOLOGO='1'),check=True)
