using System;using System.IO;using Emberfall;
public static class SkillStockProductionTests{
 static int n;static void C(bool b,string s){n++;if(!b)throw new Exception(s);}static bool Near(float a,float b)=>Math.Abs(a-b)<.002f;
 static SkillRuntime Bind(ProgressionService p,HeroClass hero){var r=new SkillRuntime(hero);SkillStockRules.Normalize(p.Profile);int i=(int)hero;r.RestoreStock(p.Profile.skillStockCounts[i],p.Profile.skillStockRemaining[i],p.Profile.skillStockPeriods[i]);r.CommitStock=(c,t,d)=>p.CommitSkillStock(hero,c,t,d);r.StockChanged=(c,t,d)=>p.TrackSkillStock(hero,c,t,d);return r;}
 public static string Run(string path){
 foreach(HeroClass hero in Enum.GetValues(typeof(HeroClass))){int skill=SkillStockRules.Skill(hero);float period=SkillStockRules.Seconds(hero),cost=GameBalance.SkillEnergyCost(hero,skill);var r=new SkillRuntime(hero);
 C(r.Charges(skill)==2&&r.RechargeRemaining(skill)==0,"fresh full bank has no hidden recovery");C(r.TryConsume(skill,1),"first charge");float energy=r.Energy;C(!r.TryConsume(skill,1)&&r.Energy==energy&&r.Charges(skill)==1,"same-frame input cannot double spend");float lockProbe=hero==HeroClass.Vanguard?.54f:hero==HeroClass.Ranger?.59f:.24f;r.Advance(lockProbe);C(!r.TryConsume(skill,1),"action protection interval rejects early chained input");r.Advance(3-lockProbe);C(r.TryConsume(skill,3)&&r.Charges(skill)==0,"second charge regardless of rank");C(Near(r.RechargeRemaining(skill),period-3),"second release cannot restart recovery");
 r.Advance(period-3-.01f);C(r.Charges(skill)==0,"no early restore");r.Advance(.02f);C(r.Charges(skill)==1&&Near(r.RechargeRemaining(skill),period-.01f),"first recovery on original schedule");r.Advance(period-.01f);C(r.Charges(skill)==2&&r.RechargeRemaining(skill)==0,"second sequential recovery clears hidden progress");
 r.Advance(100);C(r.TryConsume(skill,1)&&Near(r.RechargeRemaining(skill),period),"idle full time cannot bank another recovery");r.Advance(1);r.FillEnergy();C(r.TryConsume(skill,1),"drain bank for reduce cooldown");r.ReduceCooldowns(period+2);C(r.Charges(skill)==1&&Near(r.RechargeRemaining(skill),period-3),"reduction carries remainder into next missing charge");r.ReduceCooldowns(10000);C(r.Charges(skill)==2&&r.RechargeRemaining(skill)==0,"reduction capped at two");
 r.TryConsume(skill,1);float t=r.RechargeRemaining(skill);r.Advance(0);r.Advance(-1);r.Advance(float.NaN);r.ReduceCooldowns(float.PositiveInfinity);C(r.RechargeRemaining(skill)==t,"paused and malformed time cannot refill");r.ResetCooldowns();C(r.Charges(skill)==2&&r.RechargeRemaining(skill)==0,"committed new adventure reset fills stock");
 var debuff=new SkillRuntime(hero);debuff.TryConsume(skill,1,.7f);C(Near(debuff.RechargeRemaining(skill),period*.7f),"run cooldown modifier applies to recharge period");debuff.Advance(1);debuff.FillEnergy();debuff.TryConsume(skill,1,1);C(Near(debuff.RechargeRemaining(skill),period*.7f-1),"second cast cannot alter current queue modifier");
 var service=new ProgressionService(Path.Combine(path,hero.ToString()));service.NewGame(hero);service.Profile.level=45;service.Profile.skillRanks[skill]=1;service.Save();var live=Bind(service,hero);C(live.TryConsume(skill,1)&&Near(live.Energy,100-cost),"durable spend retains full existing energy cost");
 string build=service.BuildStateFingerprint();var draft=service.BeginBuildDraft(true);live.Advance(1);C(service.BuildStateFingerprint()==build&&draft.IsCurrent,"recharge cannot invalidate build draft or merchant confirmation");
 C(service.SaveBuildPreset(0,true)&&service.AssignSkill(0,skill)&&service.ApplyBuildPreset(0,true),"existing loadout and preset operations remain usable");C(service.Profile.skillStockCounts[(int)hero]==1&&Near(service.Profile.skillStockRemaining[(int)hero],period-1),"slot/preset changes preserve bank and progress");
 live.Advance(period);live.ResetCooldowns();service.Save();C(live.TryConsume(skill,1),"fresh durable test spend after explicit reset");
 var reload=new ProgressionService(Path.Combine(path,hero.ToString()));C(reload.Load(),"load consumed stock");var loaded=Bind(reload,hero);C(loaded.Charges(skill)==1&&Near(loaded.RechargeRemaining(skill),period),"ordinary reload cannot refill consumed use");loaded.Advance(3);reload.Save();C(reload.Load(),"reload saved recovery progress");loaded=Bind(reload,hero);C(loaded.Charges(skill)==1&&Near(loaded.RechargeRemaining(skill),period-3),"saved progress restored without wall-clock credit");loaded.Advance(1);C(loaded.TryConsume(skill,1)&&loaded.Charges(skill)==0,"second durable spend");C(reload.Load()&&Bind(reload,hero).Charges(skill)==0,"repeated reload stays empty");
 loaded=Bind(reload,hero);loaded.Advance(period*2);reload.Save();float before=loaded.Energy;string original=File.ReadAllText(reload.SaveFilePath);File.Move(reload.SaveFilePath,reload.SaveFilePath+".held");Directory.CreateDirectory(reload.SaveFilePath);
 C(!loaded.TryConsume(skill,1)&&loaded.StockPersistenceFailed&&loaded.Charges(skill)==2&&loaded.Energy==before,"failed persistence rejects charge and energy commitment");Directory.Delete(reload.SaveFilePath);File.Move(reload.SaveFilePath+".held",reload.SaveFilePath);C(File.ReadAllText(reload.SaveFilePath)==original,"failed stock save keeps old durable profile");
 reload.Profile.skillStockVersion=0;reload.Profile.skillStockCounts=null;reload.Profile.skillStockRemaining=null;reload.Profile.skillStockPeriods=null;reload.Save();C(reload.Load()&&reload.Profile.skillStockVersion==1&&Bind(reload,hero).Charges(skill)==2,"legacy migration grants initial bank once and writes version");var migrated=Bind(reload,hero);C(migrated.TryConsume(skill,1)&&reload.Load()&&Bind(reload,hero).Charges(skill)==1,"migration never repeats after first spend");
 // Isolated input budget [0,window): abundant energy, real commit/clock, no damage approximation.
 foreach(int window in new[]{3,60}){var sim=new SkillRuntime(hero);int casts=0;for(int tick=0;tick<window*100;tick++){if(tick>0)sim.Advance(.01f);sim.FillEnergy();if(sim.TryConsume(skill,1))casts++;}int expected=window==3?2:2+(int)Math.Floor((window-.001)/period);C(casts==expected,"bounded sequential cast budget "+hero+"/"+window+"s");Console.WriteLine("BUDGET "+hero+" "+window+"s: "+casts+" casts, "+(casts*cost)+" energy, "+casts+" x unchanged single-cast damage");}
 }
 var invalid=new GameProfile{skillStockVersion=1,skillStockCounts=new[]{9,-4,0,2},skillStockRemaining=new[]{float.NaN,0,float.PositiveInfinity,99f},skillStockPeriods=new[]{0f,1f,100f,8f}};SkillStockRules.Normalize(invalid);C(invalid.skillStockCounts[0]==2&&invalid.skillStockCounts[1]==0&&invalid.skillStockRemaining[3]==0,"stored data clamped conservatively and full bank clears time");
 return "PASS "+n+" production stock timing/resource/persistence/migration/budget assertions; managed JSON and filesystem boundary";
 }}
