using System;using System.IO;using System.Reflection;using System.Collections.Generic;
using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;
namespace Emberfall.Editor {
[InitializeOnLoad] public static class CombatReadabilityReview {
 const string Key="Emberfall.ReadabilityReview";const BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public;
 static int stage=-1,errors;static double next;static EnemyController enemy;static FloatingNumber number;static Vector3 contact;static readonly List<string> report=new List<string>();
 static string Root=>Path.GetFullPath("Docs/Validation/Readability");static EditorWindow view;
 static CombatReadabilityReview(){EditorApplication.update+=Tick;}
 public static void Run(){Directory.CreateDirectory(Root);SessionState.SetString("Emberfall.ValidationSaveDirectory",Root+"/Save");SessionState.SetBool(Key,true);EditorSceneManager.OpenScene("Assets/Scenes/Main.unity");view=EditorWindow.GetWindow(typeof(UnityEditor.Editor).Assembly.GetType("UnityEditor.GameView"));view.Show();view.Focus();typeof(UISkinVisualReview).GetField("view",BindingFlags.Static|BindingFlags.NonPublic).SetValue(null,view);typeof(UISkinVisualReview).GetMethod("ConfigureView",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{1704,786});MobileControls.ValidationUsesSimulation=true;MobileControls.SimulationEnabled=true;MobileControls.ValidationDpi=326;EditorApplication.isPlaying=true;}
 static void Check(bool ok,string msg){report.Add((ok?"PASS ":"FAIL ")+msg);if(!ok)errors++;}
 static void Tick(){if(!SessionState.GetBool(Key,false)||!EditorApplication.isPlaying||EditorApplication.isCompiling)return;EditorApplication.QueuePlayerLoopUpdate();if(view!=null)view.Repaint();var g=GameSession.Instance;if(g==null||g.Progression==null||EditorApplication.timeSinceStartup<next)return;
 try {
 if(g.BackgroundPaused){typeof(GameSession).GetMethod("OnApplicationPause",F).Invoke(g,new object[]{false});typeof(GameSession).GetMethod("OnApplicationFocus",F).Invoke(g,new object[]{true});}
 if(stage<0){g.StartNew(HeroClass.Vanguard);g.SetPaused(false);g.gameObject.AddComponent<UISkinViewportGuard>();stage=0;next=EditorApplication.timeSinceStartup+1;return;}
 if(stage==0){ScreenCapture.CaptureScreenshot(Root+"/hud-editor.png");g.BeginPractice(CampPracticeScenario.Stationary,10);g.StartPractice();next=EditorApplication.timeSinceStartup+.8;stage++;return;}
 if(stage==1){foreach(var n in UnityEngine.Object.FindObjectsByType<FloatingNumber>(FindObjectsSortMode.None))UnityEngine.Object.DestroyImmediate(n.gameObject);enemy=g.Enemies[0];contact=enemy.transform.position+Vector3.up*1.25f;enemy.TakeDamage(3,Vector3.forward,impact:false,contactPoint:contact);var all=UnityEngine.Object.FindObjectsByType<FloatingNumber>(FindObjectsSortMode.None);foreach(var n in all)if(n.name=="Damage")number=n;Check(number!=null,"confirmed hit admits a damage caption");next=EditorApplication.timeSinceStartup+.12;stage++;return;}
 if(stage>=2&&stage<=4){Check(number!=null,"caption remains alive during fade");if(number!=null){Check((Vector3)typeof(FloatingNumber).GetField("originAtSpawn",F).GetValue(number)==contact,"caption remains at captured world contact");Check((int)typeof(FloatingNumber).GetField("lane",F).GetValue(number)==0,"rotation keeps caption in admitted lane");int meshes=0;foreach(var r in number.GetComponentsInChildren<MeshRenderer>())if(r.enabled)meshes++;Check(meshes==0,"world text and outline meshes cannot draw duplicate faces or shadows");int count=0;foreach(var n in UnityEngine.Object.FindObjectsByType<FloatingNumber>(FindObjectsSortMode.None))if(n.name=="Damage")count++;Check(count==1,"one hit remains one active caption after rotation");ScreenCapture.CaptureScreenshot(Root+"/damage-"+(stage-2)+".png");enemy.transform.Rotate(0,95,0);g.Player.transform.Rotate(0,85,0);Camera.main.transform.RotateAround(contact,Vector3.up,8);}
 next=EditorApplication.timeSinceStartup+.48;stage++;return;}
 if(stage==5){Check(number==null,"caption retires after fade without respawning");g.EndPractice("视觉复查");var profile=g.Progression.Profile;profile.level=100;for(int i=0;i<profile.skillRanks.Length;i++)profile.skillRanks[i]=3;g.Player.RefreshStats(true);g.SetPaused(false);Time.timeScale=0;stage++;next=EditorApplication.timeSinceStartup+.4;return;}
 if(stage>=6&&stage<=8){var runtime=typeof(PlayerController).GetField("skillRuntime",F).GetValue(g.Player);var cooldowns=(float[])typeof(SkillRuntime).GetField("cooldowns",F).GetValue(runtime);float fill=(stage-5)*.25f;for(int i=0;i<cooldowns.Length;i++)cooldowns[i]=GameBalance.EffectiveCooldown(HeroClass.Vanguard,i,3)*(1-fill);ScreenCapture.CaptureScreenshot(Root+"/cooldown-"+(int)(fill*100)+".png");report.Add("Captured learned skill recovery at "+(int)(fill*100)+" percent");stage++;next=EditorApplication.timeSinceStartup+.4;return;}
 if(stage==9)Finish();
 }catch(Exception e){report.Add(e.ToString());errors++;Finish();}}
 static void Finish(){SessionState.SetBool(Key,false);File.WriteAllLines(Root+"/damage-review.txt",report);EditorApplication.isPlaying=false;EditorApplication.delayCall+=()=>EditorApplication.Exit(errors==0?0:1);}
}}
