using System;using System.IO;using System.Reflection;using System.Collections.Generic;
using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;
namespace Emberfall.Editor {
[InitializeOnLoad] public static class WorldExpansionVisualReview {
 const string Key="Emberfall.WorldExpansionReview";const BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public;
 static int stage=-1,errors;static double next;static GameObject alternate;static readonly List<string> rows=new List<string>();
 static string Root=>Path.GetFullPath("Docs/Validation/ExpandedWorld");
 static WorldExpansionVisualReview(){EditorApplication.update+=Tick;Application.logMessageReceived+=Log;}
 public static void Run(){Directory.CreateDirectory(Root);SessionState.SetString("Emberfall.ValidationSaveDirectory",Root+"/Save");SessionState.SetBool(Key,true);EditorSceneManager.OpenScene("Assets/Scenes/Main.unity");EditorApplication.isPlaying=true;}
 static void Log(string m,string t,LogType type){if(SessionState.GetBool(Key,false)&&(type==LogType.Error||type==LogType.Exception)&&!t.Contains("UnityEditor.Search")){errors++;rows.Add(m+"\n"+t);}}
 static void Check(bool ok,string m){rows.Add((ok?"PASS ":"FAIL ")+m);if(!ok)errors++;}
 static GameObject World(GameSession g)=>(GameObject)typeof(GameSession).GetField("world",F).GetValue(g);
 static void Tick(){if(!SessionState.GetBool(Key,false)||!EditorApplication.isPlaying||EditorApplication.isCompiling)return;EditorApplication.QueuePlayerLoopUpdate();var g=GameSession.Instance;if(g==null||g.Progression==null||EditorApplication.timeSinceStartup<next)return;try {
 if(g.BackgroundPaused){typeof(GameSession).GetMethod("OnApplicationPause",F).Invoke(g,new object[]{false});typeof(GameSession).GetMethod("OnApplicationFocus",F).Invoke(g,new object[]{true});}
 if(stage<0){g.StartNew(HeroClass.Vanguard);g.SetPaused(false);stage=0;next=EditorApplication.timeSinceStartup+2;return;}
 if(stage==0&&typeof(GameSession).GetField("wildernessPopulationRoutine",F).GetValue(g)!=null){next=EditorApplication.timeSinceStartup+.5;return;}
 if(stage==0){Check(g.ArenaRadius==32,"camp traversal radius is 32m");Check(g.Enemies.Count>=24,"expanded camp has at least 24 creatures");Check(WorldTraversal.CanReach(new Vector3(0,0,-10),new Vector3(27,0,13)),"camp outer ridge is reachable");Capture("expanded-camp",new Vector3(16,27,-36),new Vector3(0,1,0),23);Capture("outer-ridge",new Vector3(-30,10,-29),new Vector3(-22,1,-15),8);typeof(GameSession).GetMethod("ChangeZone",F).Invoke(g,new object[]{true});}
 if(stage==1){Check(g.ArenaRadius==28&&g.TotalWaves==5,"standard dungeon radius and five-stage pacing");Check(WorldTerrain.Height(new Vector3(-14,0,-11))>2,"dungeon side gallery relief exceeds 2m");Check(WorldTraversal.CanReach(new Vector3(0,0,-9),new Vector3(21,0,15)),"expanded eastern dungeon approach is reachable");g.Player.Teleport(new Vector3(-15,0,-16));Check(Mathf.Abs(g.Player.transform.position.y-WorldTraversal.SurfaceHeight(g.Player.transform.position))<.1f,"hero stays grounded on dungeon hillside");var shader=Resources.Load<Shader>("WorldArt/WeatheredWorld");Check(shader.isSupported&&!ShaderUtil.ShaderHasError(shader),"terrain shader supports Metal");Capture("expanded-dungeon",new Vector3(22,23,-34),new Vector3(0,1,0),20);Capture("dungeon-gallery-relief",new Vector3(-29,8,-25),new Vector3(-15,1,-10),8);World(g).SetActive(false);foreach(var e in g.Enemies)if(e!=null)e.gameObject.SetActive(false);alternate=WorldBuilder.Build(ZoneKind.Dungeon,100);}
 if(stage==2){Check(WorldTerrain.Enabled,"forest chapter also has relief");Check(WorldTraversal.CanReach(new Vector3(0,0,-12),new Vector3(0,0,14)),"forest chapter entrance and exit remain connected");Capture("forest-chapter",new Vector3(19,17,-26),new Vector3(0,1,0),15);alternate.SetActive(false);UnityEngine.Object.Destroy(alternate);alternate=WorldBuilder.Build(ZoneKind.Dungeon,102);}
 if(stage==3){Check(WorldTraversal.CanReach(new Vector3(0,0,-12),new Vector3(0,0,14)),"mine chapter route remains connected");Capture("mine-chapter",new Vector3(18,18,-25),new Vector3(0,1,0),15);alternate.SetActive(false);UnityEngine.Object.Destroy(alternate);alternate=WorldBuilder.Build(ZoneKind.Dungeon,22);}
 if(stage==4){Check(WorldTerrain.Height(new Vector3(9,0,0))==0,"flooded crossing keeps water datum");Check(WorldTraversal.CanReach(new Vector3(0,0,-12),new Vector3(0,0,14)),"flooded tactical bridge remains connected");Capture("flooded-room",new Vector3(17,16,-23),new Vector3(0,1,0),14);alternate.SetActive(false);UnityEngine.Object.Destroy(alternate);World(g).SetActive(true);typeof(GameSession).GetMethod("ChangeZone",F).Invoke(g,new object[]{false});}
 if(stage==5){for(int i=0;i<3;i++){var watch=System.Diagnostics.Stopwatch.StartNew();typeof(GameSession).GetMethod("ChangeZone",F).Invoke(g,new object[]{false});watch.Stop();rows.Add("warm camp return synchronous ms="+watch.Elapsed.TotalMilliseconds.ToString("0.00"));}Finish();return;}
 stage++;next=EditorApplication.timeSinceStartup+1.5;
 }catch(Exception e){errors++;rows.Add(e.ToString());Finish();}}
 static void Capture(string name,Vector3 at,Vector3 target,float size){var obj=new GameObject("Expansion review camera");var cam=obj.AddComponent<Camera>();cam.CopyFrom(Camera.main);cam.transform.position=at;cam.transform.LookAt(target);cam.orthographic=true;cam.orthographicSize=size;cam.ResetProjectionMatrix();var rt=new RenderTexture(1704,1100,24){antiAliasing=4};var tex=new Texture2D(1704,1100,TextureFormat.RGB24,false);var old=RenderTexture.active;try{cam.targetTexture=rt;cam.aspect=1704f/1100;cam.Render();RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,1704,1100),0,0);tex.Apply();File.WriteAllBytes(Root+"/"+name+".png",tex.EncodeToPNG());}finally{cam.targetTexture=null;RenderTexture.active=old;rt.Release();UnityEngine.Object.DestroyImmediate(tex);UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(obj);}}
 static void Finish(){SessionState.SetBool(Key,false);File.WriteAllLines(Root+"/review.txt",rows);EditorApplication.isPlaying=false;EditorApplication.delayCall+=()=>EditorApplication.Exit(errors==0?0:1);}
}}
